"""Inspect a SolidWorks Codex backup report and classify restore readiness."""
from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime
from pathlib import Path
from typing import Any

ALLOWED_SUFFIXES = {".sldprt", ".sldasm", ".slddrw", ".SLDPRT", ".SLDASM", ".SLDDRW"}


def sha256(path: Path) -> str | None:
    if not path.exists() or not path.is_file():
        return None
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def size(path: Path) -> int | None:
    return path.stat().st_size if path.exists() and path.is_file() else None


def load_report(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8-sig"))
    if not isinstance(data, dict):
        raise ValueError("backup report must be a JSON object")
    if not isinstance(data.get("files"), list):
        raise ValueError("backup report must contain a files array")
    return data


def classify(entry: Any) -> dict[str, Any]:
    errors: list[str] = []
    if not isinstance(entry, dict):
        return {"source": None, "backup": None, "status": "error", "errors": ["entry_not_object"], "restorable": False}
    source = Path(entry.get("source", "")) if entry.get("source") else None
    backup = Path(entry.get("backup", "")) if entry.get("backup") else None
    if not source:
        errors.append("source_missing")
    if not backup:
        errors.append("backup_path_missing")
    if source and source.suffix not in ALLOWED_SUFFIXES:
        errors.append("unsupported_source_type")
    if backup and backup.suffix not in ALLOWED_SUFFIXES:
        errors.append("unsupported_backup_type")
    source_exists = bool(source and source.exists() and source.is_file())
    backup_exists = bool(backup and backup.exists() and backup.is_file())
    if source and not source_exists:
        errors.append("source_missing")
    if backup and not backup_exists:
        errors.append("backup_missing")
    source_hash = sha256(source) if source else None
    backup_hash = sha256(backup) if backup else None
    if "backup_missing" in errors:
        status = "backup_missing"
    elif "source_missing" in errors:
        status = "source_missing"
    elif errors:
        status = "error"
    elif source_hash == backup_hash:
        status = "unchanged"
    else:
        status = "changed"
    return {
        "source": str(source) if source else None,
        "backup": str(backup) if backup else None,
        "status": status,
        "errors": errors,
        "restorable": backup_exists and not any(e in errors for e in ["backup_missing", "backup_path_missing", "unsupported_backup_type"]),
        "source_exists": source_exists,
        "backup_exists": backup_exists,
        "source_size": size(source) if source else None,
        "backup_size": size(backup) if backup else None,
        "source_sha256": source_hash,
        "backup_sha256": backup_hash,
    }


def build_status(report_path: Path) -> dict[str, Any]:
    report = load_report(report_path)
    files = [classify(entry) for entry in report["files"]]
    summary: dict[str, int] = {"changed": 0, "unchanged": 0, "source_missing": 0, "backup_missing": 0, "error": 0, "restorable": 0}
    for item in files:
        status = item["status"]
        summary[status] = summary.get(status, 0) + 1
        if item.get("restorable"):
            summary["restorable"] += 1
    ok = all(not item["errors"] for item in files)
    return {
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "ok": ok,
        "report": str(report_path),
        "backup_root": report.get("backup_root"),
        "file_count": len(files),
        "summary": summary,
        "files": files,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--report", required=True, help="Backup report JSON generated by sw_backup.py")
    parser.add_argument("--out", default="tools/solidworks_codex/reports/backup_status.json")
    args = parser.parse_args()
    result = build_status(Path(args.report))
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(result, ensure_ascii=False, indent=2))
    raise SystemExit(0 if result["ok"] else 1)


if __name__ == "__main__":
    main()
