"""Generate reviewable VBA macros for adding mates between preselected entities.

The generated macro expects the user to preselect the two entities in SolidWorks before
running. This avoids fragile blind entity naming in partially complete assemblies.
"""
from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path

MATE_TYPES = {
    "coincident": 0,
    "concentric": 1,
    "tangent": 4,
    "distance": 5,
    "angle": 6,
    "parallel": 3,
    "perpendicular": 2,
}


def macro(mate_type: str, distance_m: float, angle_deg: float, flip: bool) -> str:
    mate_code = MATE_TYPES[mate_type]
    flip_vba = "True" if flip else "False"
    angle_rad = angle_deg * 3.141592653589793 / 180.0
    return f'''Option Explicit

' Generated by SolidWorks Codex.
' Preselect exactly two mate entities before running this macro.
' Mate type: {mate_type}

Dim swApp As Object
Dim Part As Object
Dim Assembly As Object
Dim MateFeature As Object
Dim mateError As Long

Sub main()
    Set swApp = Application.SldWorks
    Set Part = swApp.ActiveDoc
    If Part Is Nothing Then
        MsgBox "No active document. Open an assembly and preselect two entities."
        Exit Sub
    End If
    If Part.GetType <> 2 Then
        MsgBox "Active document is not an assembly."
        Exit Sub
    End If
    Set Assembly = Part
    If Part.SelectionManager.GetSelectedObjectCount2(-1) < 2 Then
        MsgBox "Preselect exactly two mate entities before running."
        Exit Sub
    End If

    Set MateFeature = Assembly.AddMate5({mate_code}, -1, {flip_vba}, {distance_m:.9f}, {distance_m:.9f}, {distance_m:.9f}, {angle_rad:.9f}, {angle_rad:.9f}, {angle_rad:.9f}, 0#, 0#, 0#, False, False, 0, mateError)
    Part.ForceRebuild3 False
    If mateError <> 0 Then
        MsgBox "Mate created with error code: " & CStr(mateError)
    Else
        MsgBox "Mate created: {mate_type}"
    End If
End Sub
'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mate", required=True, choices=sorted(MATE_TYPES))
    parser.add_argument("--distance-mm", type=float, default=0.0)
    parser.add_argument("--angle-deg", type=float, default=0.0)
    parser.add_argument("--flip", action="store_true")
    parser.add_argument("--out", default="tools/solidworks_codex/macros/mate_preselect.swp.vba")
    parser.add_argument("--manifest", default="tools/solidworks_codex/reports/mate_macro_manifest.json")
    args = parser.parse_args()
    text = macro(args.mate, args.distance_mm / 1000.0, args.angle_deg, args.flip)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    manifest = {
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "mate": args.mate,
        "distance_mm": args.distance_mm,
        "angle_deg": args.angle_deg,
        "flip": args.flip,
        "macro": str(out.resolve()),
        "preselect_required": True,
        "review_required": True,
        "note": "Open assembly, preselect exactly two entities, review macro, then run.",
    }
    mpath = Path(args.manifest)
    mpath.parent.mkdir(parents=True, exist_ok=True)
    mpath.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(manifest, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
