"""Generate reviewable VBA macros for adding mates between preselected entities.

The generated macro expects the user to preselect the two entities in SolidWorks before
running. This avoids fragile blind entity naming in partially complete assemblies.
"""
from __future__ import annotations

import argparse
import json
import math
from datetime import datetime
from pathlib import Path

MATE_TYPES = {
    "coincident": 0,
    "concentric": 1,
    "tangent": 4,
    "distance": 5,
    "limit_distance": 5,
    "angle": 6,
    "limit_angle": 6,
    "symmetry": 8,
    "cam": 9,
    "cam_follower": 9,
    "gear": 10,
    "slot": 21,
    "parallel": 3,
    "perpendicular": 2,
}


def finite_or_none(value: float) -> float | None:
    return value if math.isfinite(value) else None


def macro(
    mate_type: str,
    distance_m: float,
    angle_deg: float,
    flip: bool,
    distance_min_m: float | None = None,
    distance_max_m: float | None = None,
    angle_min_deg: float | None = None,
    angle_max_deg: float | None = None,
    gear_ratio_numerator: float = 1.0,
    gear_ratio_denominator: float = 1.0,
    slot_constraint_type: int = 0,
    slot_distance_m: float | None = None,
    slot_percent: float | None = None,
) -> str:
    if mate_type == "slot":
        return slot_macro(slot_constraint_type, slot_distance_m, slot_percent)
    mate_code = MATE_TYPES[mate_type]
    flip_vba = "True" if flip else "False"
    required_selection_count = 3 if mate_type == "symmetry" else 2
    selection_phrase = "exactly three mate entities" if required_selection_count == 3 else "exactly two mate entities"
    angle_rad = angle_deg * 3.141592653589793 / 180.0
    distance_upper_m = distance_max_m if distance_max_m is not None else distance_m
    distance_lower_m = distance_min_m if distance_min_m is not None else distance_m
    angle_upper_rad = (angle_max_deg * 3.141592653589793 / 180.0) if angle_max_deg is not None else angle_rad
    angle_lower_rad = (angle_min_deg * 3.141592653589793 / 180.0) if angle_min_deg is not None else angle_rad
    gear_numerator = float(gear_ratio_numerator or 1.0)
    gear_denominator = float(gear_ratio_denominator or 1.0)
    return f'''Option Explicit

' Generated by SolidWorks Codex.
' Preselect {selection_phrase} before running this macro.
' Mate type: {mate_type}

Dim swApp As Object
Dim Part As Object
Dim Assembly As Object
Dim MateFeature As Object
Dim mateError As Long

Sub main()
    Set swApp = Application.SldWorks
    Set Part = swApp.ActiveDoc
    If Part Is Nothing Then
        MsgBox "No active document. Open an assembly and preselect {required_selection_count} entities."
        Exit Sub
    End If
    If Part.GetType <> 2 Then
        MsgBox "Active document is not an assembly."
        Exit Sub
    End If
    Set Assembly = Part
    If Part.SelectionManager.GetSelectedObjectCount2(-1) < {required_selection_count} Then
        MsgBox "Preselect {selection_phrase} before running."
        Exit Sub
    End If

    Set MateFeature = Assembly.AddMate5({mate_code}, -1, {flip_vba}, {distance_m:.9f}, {distance_upper_m:.9f}, {distance_lower_m:.9f}, {gear_numerator:.9f}, {gear_denominator:.9f}, {angle_rad:.9f}, {angle_upper_rad:.9f}, {angle_lower_rad:.9f}, 0#, False, False, 0, mateError)
    Part.ForceRebuild3 False
    If mateError <> 0 Then
        MsgBox "Mate created with error code: " & CStr(mateError)
    Else
        MsgBox "Mate created: {mate_type}"
    End If
End Sub
'''


def slot_macro(slot_constraint_type: int, slot_distance_m: float | None = None, slot_percent: float | None = None) -> str:
    distance_line = ""
    if slot_distance_m is not None:
        distance_line = f"    MateData.Distance = {slot_distance_m:.9f}\n"
    percent_line = ""
    if slot_percent is not None:
        percent_line = f"    MateData.Percent = {slot_percent:.9f}\n"
    return f'''Option Explicit

' Generated by SolidWorks Codex.
' Preselect exactly two mate entities before running this macro.
' Mate type: slot

Dim swApp As Object
Dim Part As Object
Dim Assembly As Object
Dim MateData As Object
Dim MateFeature As Object

Sub main()
    Set swApp = Application.SldWorks
    Set Part = swApp.ActiveDoc
    If Part Is Nothing Then
        MsgBox "No active document. Open an assembly and preselect 2 entities."
        Exit Sub
    End If
    If Part.GetType <> 2 Then
        MsgBox "Active document is not an assembly."
        Exit Sub
    End If
    Set Assembly = Part
    If Part.SelectionManager.GetSelectedObjectCount2(-1) < 2 Then
        MsgBox "Preselect exactly two mate entities before running."
        Exit Sub
    End If

    Set MateData = Assembly.CreateMateData(21)
    MateData.EntitiesToMate = Array(Part.SelectionManager.GetSelectedObject6(1, -1), Part.SelectionManager.GetSelectedObject6(2, -1))
    MateData.Constraint = {int(slot_constraint_type)}
{distance_line}{percent_line}    Set MateFeature = Assembly.CreateMate(MateData)
    Part.ForceRebuild3 False
    If MateFeature Is Nothing Then
        MsgBox "Slot mate was not created."
    Else
        MsgBox "Mate created: slot"
    End If
End Sub
'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mate", required=True, choices=sorted(MATE_TYPES))
    parser.add_argument("--distance-mm", type=float, default=0.0)
    parser.add_argument("--distance-min-mm", type=float, default=float("nan"))
    parser.add_argument("--distance-max-mm", type=float, default=float("nan"))
    parser.add_argument("--angle-deg", type=float, default=0.0)
    parser.add_argument("--angle-min-deg", type=float, default=float("nan"))
    parser.add_argument("--angle-max-deg", type=float, default=float("nan"))
    parser.add_argument("--gear-ratio-numerator", type=float, default=1.0)
    parser.add_argument("--gear-ratio-denominator", type=float, default=1.0)
    parser.add_argument("--slot-constraint-type", type=int, default=0)
    parser.add_argument("--slot-distance-mm", type=float, default=float("nan"))
    parser.add_argument("--slot-percent", type=float, default=float("nan"))
    parser.add_argument("--flip", action="store_true")
    parser.add_argument("--out", default="tools/solidworks_codex/macros/mate_preselect.swp.vba")
    parser.add_argument("--manifest", default="tools/solidworks_codex/reports/mate_macro_manifest.json")
    args = parser.parse_args()
    distance_min_mm = finite_or_none(args.distance_min_mm)
    distance_max_mm = finite_or_none(args.distance_max_mm)
    angle_min_deg = finite_or_none(args.angle_min_deg)
    angle_max_deg = finite_or_none(args.angle_max_deg)
    slot_distance_mm = finite_or_none(args.slot_distance_mm)
    slot_percent = finite_or_none(args.slot_percent)
    text = macro(
        args.mate,
        args.distance_mm / 1000.0,
        args.angle_deg,
        args.flip,
        None if distance_min_mm is None else distance_min_mm / 1000.0,
        None if distance_max_mm is None else distance_max_mm / 1000.0,
        angle_min_deg,
        angle_max_deg,
        args.gear_ratio_numerator,
        args.gear_ratio_denominator,
        args.slot_constraint_type,
        None if slot_distance_mm is None else slot_distance_mm / 1000.0,
        slot_percent,
    )
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    manifest = {
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "mate": args.mate,
        "distance_mm": args.distance_mm,
        "distance_min_mm": distance_min_mm,
        "distance_max_mm": distance_max_mm,
        "angle_deg": args.angle_deg,
        "angle_min_deg": angle_min_deg,
        "angle_max_deg": angle_max_deg,
        "gear_ratio_numerator": args.gear_ratio_numerator,
        "gear_ratio_denominator": args.gear_ratio_denominator,
        "slot_constraint_type": args.slot_constraint_type,
        "slot_distance_mm": slot_distance_mm,
        "slot_percent": slot_percent,
        "flip": args.flip,
        "macro": str(out.resolve()),
        "preselect_required": True,
        "review_required": True,
        "note": "Open assembly, preselect exactly two entities, review macro, then run.",
    }
    mpath = Path(args.manifest)
    mpath.parent.mkdir(parents=True, exist_ok=True)
    mpath.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(manifest, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
