"""Restore files from a SolidWorks Codex backup report.

Default mode is dry-run: it validates the backup report and records the exact
copy operations that would be performed. Use --apply to overwrite source files
with their backup copies.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from datetime import datetime
from pathlib import Path
from typing import Any

ALLOWED_SUFFIXES = {".sldprt", ".sldasm", ".slddrw", ".SLDPRT", ".SLDASM", ".SLDDRW"}


def sha256(path: Path) -> str | None:
    if not path.exists() or not path.is_file():
        return None
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def size(path: Path) -> int | None:
    return path.stat().st_size if path.exists() and path.is_file() else None


def load_report(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8-sig"))
    if not isinstance(data, dict):
        raise ValueError("backup report must be a JSON object")
    if not isinstance(data.get("files"), list):
        raise ValueError("backup report must contain a files array")
    return data


def validate_entry(entry: Any) -> tuple[Path | None, Path | None, list[str]]:
    errors: list[str] = []
    if not isinstance(entry, dict):
        return None, None, ["entry_not_object"]
    source_raw = entry.get("source")
    backup_raw = entry.get("backup")
    if not source_raw:
        errors.append("source_missing")
    if not backup_raw:
        errors.append("backup_path_missing")
    source = Path(source_raw) if source_raw else None
    backup = Path(backup_raw) if backup_raw else None
    if source and source.suffix not in ALLOWED_SUFFIXES:
        errors.append("unsupported_source_type")
    if backup and backup.suffix not in ALLOWED_SUFFIXES:
        errors.append("unsupported_backup_type")
    if backup and not backup.exists():
        errors.append("backup_missing")
    if backup and backup.exists() and not backup.is_file():
        errors.append("backup_not_file")
    if source and source.exists() and not source.is_file():
        errors.append("source_not_file")
    if source and not source.parent.exists():
        errors.append("source_parent_missing")
    return source, backup, errors


def restore(report_path: Path, apply: bool) -> dict[str, Any]:
    data = load_report(report_path)
    items = []
    for entry in data["files"]:
        source, backup, errors = validate_entry(entry)
        before_hash = sha256(source) if source else None
        backup_hash = sha256(backup) if backup else None
        status = "error" if errors else ("restored" if apply else "planned")
        if apply and not errors and source and backup:
            source.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(backup, source)
        after_hash = sha256(source) if source else None
        items.append({
            "source": str(source) if source else None,
            "backup": str(backup) if backup else None,
            "status": status,
            "errors": errors,
            "source_size_before": size(source) if source else None,
            "source_sha256_before": before_hash,
            "source_size_after": size(source) if source else None,
            "source_sha256_after": after_hash,
            "backup_size": size(backup) if backup else None,
            "backup_sha256": backup_hash,
        })
    ok = all(not item["errors"] for item in items)
    return {
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "ok": ok,
        "applied": apply,
        "report": str(report_path),
        "backup_root": data.get("backup_root"),
        "file_count": len(items),
        "files": items,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--report", required=True, help="Backup report JSON generated by sw_backup.py")
    parser.add_argument("--apply", action="store_true", help="Actually overwrite source files with backup files")
    parser.add_argument("--out", default="tools/solidworks_codex/reports/restore_backup.json")
    args = parser.parse_args()

    result = restore(Path(args.report), args.apply)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(result, ensure_ascii=False, indent=2))
    raise SystemExit(0 if result["ok"] else 1)


if __name__ == "__main__":
    main()
