"""Generate reviewable SolidWorks VBA macros for common mechanical part templates.

This generator does not execute SolidWorks. It writes VBA macro text plus a JSON
manifest so Codex/user can review parameters before running in SolidWorks.
"""
from __future__ import annotations

import argparse
import json
import math
from datetime import datetime
from pathlib import Path
from typing import Any


def mm(value: float) -> float:
    return value / 1000.0


def vba_header(name: str) -> str:
    return f'''Option Explicit

' Generated by SolidWorks Codex template generator.
' Template: {name}
' Units: input millimeters converted to SolidWorks meters.

Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()
    Set swApp = Application.SldWorks
    Set Part = swApp.NewPart
    If Part Is Nothing Then
        MsgBox "Failed to create new part. Check SolidWorks templates."
        Exit Sub
    End If
'''


def vba_footer() -> str:
    return '''
    Part.ViewZoomtofit2
    Part.ForceRebuild3 False
End Sub
'''


def boss_cylinder(radius_m: float, depth_m: float, sketch_name: str = "Sketch-Base") -> str:
    return f'''
    boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
    Part.SketchManager.InsertSketch True
    Part.SketchManager.CreateCircleByRadius 0#, 0#, 0#, {radius_m:.9f}
    Part.SketchManager.InsertSketch True
    Part.FeatureManager.FeatureExtrusion2 True, False, False, 0, 0, {depth_m:.9f}, 0#, False, False, False, False, 0#, 0#, False, False, False, False, True, True, True, 0, 0#, False
'''


def cut_cylinder(radius_m: float, depth_m: float) -> str:
    return f'''
    boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
    Part.SketchManager.InsertSketch True
    Part.SketchManager.CreateCircleByRadius 0#, 0#, 0#, {radius_m:.9f}
    Part.SketchManager.InsertSketch True
    Part.FeatureManager.FeatureCut3 True, False, False, 1, 0, {depth_m:.9f}, {depth_m:.9f}, False, False, False, False, 0#, 0#, False, False, False, False, False, True, True, True, True, False, 0, 0, False
'''


def circular_holes(count: int, pcd_m: float, hole_radius_m: float, depth_m: float) -> str:
    lines = [
        "    boolstatus = Part.Extension.SelectByID2(\"Front Plane\", \"PLANE\", 0, 0, 0, False, 0, Nothing, 0)",
        "    Part.SketchManager.InsertSketch True",
    ]
    for i in range(count):
        angle = 2 * math.pi * i / count
        x = math.cos(angle) * pcd_m / 2
        y = math.sin(angle) * pcd_m / 2
        lines.append(f"    Part.SketchManager.CreateCircleByRadius {x:.9f}, {y:.9f}, 0#, {hole_radius_m:.9f}")
    lines += [
        "    Part.SketchManager.InsertSketch True",
        f"    Part.FeatureManager.FeatureCut3 True, False, False, 1, 0, {depth_m:.9f}, {depth_m:.9f}, False, False, False, False, 0#, 0#, False, False, False, False, False, True, True, True, True, False, 0, 0, False",
    ]
    return "\n".join(lines) + "\n"


def sleeve(args: argparse.Namespace) -> str:
    return vba_header("sleeve") + boss_cylinder(mm(args.outer_diameter_mm) / 2, mm(args.length_mm)) + cut_cylinder(mm(args.inner_diameter_mm) / 2, mm(args.length_mm) * 1.2) + vba_footer()


def spacer(args: argparse.Namespace) -> str:
    return vba_header("spacer") + boss_cylinder(mm(args.outer_diameter_mm) / 2, mm(args.length_mm)) + cut_cylinder(mm(args.inner_diameter_mm) / 2, mm(args.length_mm) * 1.2) + vba_footer()


def flange(args: argparse.Namespace) -> str:
    body = vba_header("flange")
    body += boss_cylinder(mm(args.outer_diameter_mm) / 2, mm(args.thickness_mm))
    body += cut_cylinder(mm(args.center_bore_mm) / 2, mm(args.thickness_mm) * 1.2)
    body += circular_holes(args.hole_count, mm(args.hole_pcd_mm), mm(args.hole_diameter_mm) / 2, mm(args.thickness_mm) * 1.2)
    body += vba_footer()
    return body


def endcap(args: argparse.Namespace) -> str:
    body = vba_header("endcap")
    body += boss_cylinder(mm(args.outer_diameter_mm) / 2, mm(args.thickness_mm))
    if args.center_bore_mm > 0:
        body += cut_cylinder(mm(args.center_bore_mm) / 2, mm(args.thickness_mm) * 1.2)
    if args.hole_count > 0:
        body += circular_holes(args.hole_count, mm(args.hole_pcd_mm), mm(args.hole_diameter_mm) / 2, mm(args.thickness_mm) * 1.2)
    body += vba_footer()
    return body


def rectangle_plate(width_m: float, height_m: float, thickness_m: float) -> str:
    x = width_m / 2
    y = height_m / 2
    return f'''
    boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
    Part.SketchManager.InsertSketch True
    Part.SketchManager.CreateCornerRectangle {-x:.9f}, {-y:.9f}, 0#, {x:.9f}, {y:.9f}, 0#
    Part.SketchManager.InsertSketch True
    Part.FeatureManager.FeatureExtrusion2 True, False, False, 0, 0, {thickness_m:.9f}, 0#, False, False, False, False, 0#, 0#, False, False, False, False, True, True, True, 0, 0#, False
'''


def rectangular_holes(x_spacing_m: float, y_spacing_m: float, hole_radius_m: float, depth_m: float) -> str:
    coords = [(-x_spacing_m / 2, -y_spacing_m / 2), (x_spacing_m / 2, -y_spacing_m / 2), (x_spacing_m / 2, y_spacing_m / 2), (-x_spacing_m / 2, y_spacing_m / 2)]
    lines = [
        "    boolstatus = Part.Extension.SelectByID2(\"Front Plane\", \"PLANE\", 0, 0, 0, False, 0, Nothing, 0)",
        "    Part.SketchManager.InsertSketch True",
    ]
    for x, y in coords:
        lines.append(f"    Part.SketchManager.CreateCircleByRadius {x:.9f}, {y:.9f}, 0#, {hole_radius_m:.9f}")
    lines += [
        "    Part.SketchManager.InsertSketch True",
        f"    Part.FeatureManager.FeatureCut3 True, False, False, 1, 0, {depth_m:.9f}, {depth_m:.9f}, False, False, False, False, 0#, 0#, False, False, False, False, False, True, True, True, True, False, 0, 0, False",
    ]
    return "\n".join(lines) + "\n"


def motor_adapter(args: argparse.Namespace) -> str:
    body = vba_header("motor_adapter")
    body += rectangle_plate(mm(args.plate_width_mm), mm(args.plate_height_mm), mm(args.thickness_mm))
    if args.center_bore_mm > 0:
        body += cut_cylinder(mm(args.center_bore_mm) / 2, mm(args.thickness_mm) * 1.2)
    body += rectangular_holes(mm(args.motor_hole_x_mm), mm(args.motor_hole_y_mm), mm(args.hole_diameter_mm) / 2, mm(args.thickness_mm) * 1.2)
    if args.hole_count > 0:
        body += circular_holes(args.hole_count, mm(args.hole_pcd_mm), mm(args.hole_diameter_mm) / 2, mm(args.thickness_mm) * 1.2)
    body += vba_footer()
    return body


def bearing_retainer(args: argparse.Namespace) -> str:
    body = vba_header("bearing_retainer")
    body += boss_cylinder(mm(args.outer_diameter_mm) / 2, mm(args.thickness_mm))
    body += cut_cylinder(mm(args.center_bore_mm) / 2, mm(args.thickness_mm) * 1.2)
    # Optional shallow bearing relief/recess approximation as a second larger cut.
    if args.bearing_outer_diameter_mm > args.center_bore_mm and args.recess_depth_mm > 0:
        body += cut_cylinder(mm(args.bearing_outer_diameter_mm) / 2, mm(args.recess_depth_mm))
    if args.hole_count > 0:
        body += circular_holes(args.hole_count, mm(args.hole_pcd_mm), mm(args.hole_diameter_mm) / 2, mm(args.thickness_mm) * 1.2)
    body += vba_footer()
    return body
def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    parser.add_argument("--template", required=True, choices=["sleeve", "spacer", "flange", "endcap", "motor_adapter", "bearing_retainer"])
    parser.add_argument("--out", default="tools/solidworks_codex/macros/generated_template.swp.vba")
    parser.add_argument("--manifest", default="tools/solidworks_codex/reports/template_manifest.json")
    parser.add_argument("--outer-diameter-mm", type=float, default=40)
    parser.add_argument("--inner-diameter-mm", type=float, default=20)
    parser.add_argument("--length-mm", type=float, default=20)
    parser.add_argument("--thickness-mm", type=float, default=8)
    parser.add_argument("--center-bore-mm", type=float, default=12)
    parser.add_argument("--hole-count", type=int, default=4)
    parser.add_argument("--hole-pcd-mm", type=float, default=32)
    parser.add_argument("--hole-diameter-mm", type=float, default=4.5)
    parser.add_argument("--plate-width-mm", type=float, default=60)
    parser.add_argument("--plate-height-mm", type=float, default=60)
    parser.add_argument("--motor-hole-x-mm", type=float, default=31)
    parser.add_argument("--motor-hole-y-mm", type=float, default=31)
    parser.add_argument("--bearing-outer-diameter-mm", type=float, default=28)
    parser.add_argument("--recess-depth-mm", type=float, default=2)
    return parser


def validate(args: argparse.Namespace) -> None:
    positive = ["outer_diameter_mm"]
    if args.template in {"sleeve", "spacer"}:
        positive += ["inner_diameter_mm", "length_mm"]
        if args.inner_diameter_mm >= args.outer_diameter_mm:
            raise ValueError("inner diameter must be smaller than outer diameter")
    if args.template in {"flange", "endcap", "motor_adapter", "bearing_retainer"}:
        positive += ["thickness_mm"]
        if args.template == "motor_adapter":
            positive += ["plate_width_mm", "plate_height_mm", "motor_hole_x_mm", "motor_hole_y_mm"]
        if args.template == "bearing_retainer":
            positive += ["bearing_outer_diameter_mm"]
        if args.center_bore_mm < 0:
            raise ValueError("center bore cannot be negative")
        if args.center_bore_mm >= args.outer_diameter_mm:
            raise ValueError("center bore must be smaller than outer diameter")
        if args.hole_count < 0:
            raise ValueError("hole count cannot be negative")
        if args.hole_count and (args.hole_pcd_mm <= 0 or args.hole_diameter_mm <= 0):
            raise ValueError("hole PCD and diameter must be positive when hole_count > 0")
    for name in positive:
        if getattr(args, name) <= 0:
            raise ValueError(f"{name} must be positive")


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    validate(args)
    generator = {"sleeve": sleeve, "spacer": spacer, "flange": flange, "endcap": endcap, "motor_adapter": motor_adapter, "bearing_retainer": bearing_retainer}[args.template]
    macro = generator(args)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(macro, encoding="utf-8")
    manifest = {
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "template": args.template,
        "macro": str(out.resolve()),
        "parameters": vars(args),
        "review_required": True,
        "note": "Review generated VBA before running in SolidWorks.",
    }
    mpath = Path(args.manifest)
    mpath.parent.mkdir(parents=True, exist_ok=True)
    mpath.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(manifest, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()

