param(
    [Parameter(Position=0)]
    [ValidateSet('probe','inspect','backup','backup-status','restore-backup','set-dimension','safe-set-dimension','mcp-tools','start-probe','start-inspect','summary','compare','change-verify','assembly-contract','part-geometry-validate','visual-validate','motion-sweep-lite','engineering-lite','rebuild','start-rebuild','export','mass','start-mass','audit','component-state','start-component-state','component-insert','start-component-insert','feature-state','start-feature-state','part-feature-execute','start-part-feature-execute','metadata-execute','start-metadata-execute','interference','start-interference','template-macro','issue-report','mate-macro','mate-group-macro','mate-group-execute','selection-report','start-selection-report','session-snapshot','start-session-snapshot','preflight','design-review','change-plan','workflow-plan','report-search','report-context','model-understand','assembly-diagnose','assembly-repair-plan','interface-index','mate-group-plan','mate-group-validate','mate-selection-check','mate-group-execution-check','mate-group-live-protocol','assembly-review-pipeline','worklog','handoff-bundle','tool-catalog','offline-demo','public-copy-guard','github-readiness','repo-health','release-tree','capability-matrix','finalize','live-gate')]
    [string]$Command = 'probe',

    [string]$Out = '', [string]$Model = '', [string]$Dimension = '', [double]$ValueM = [double]::NaN,
    [switch]$Save, [switch]$Apply, [string[]]$Files = @(), [string]$Report = '', [string]$Before = '', [string]$After = '',
    [string]$JsonOut = '', [string]$Target = '', [string]$Component = '', [string]$Action = '', [string]$View = 'auto',
    [string]$TargetFeature = '', [string]$ReorderPosition = 'after',
    [string]$Template = '', [double]$OuterDiameterMm = [double]::NaN, [double]$InnerDiameterMm = [double]::NaN,
    [double]$LengthMm = [double]::NaN, [double]$ThicknessMm = [double]::NaN, [double]$CenterBoreMm = [double]::NaN,
    [int]$HoleCount = -1, [double]$HolePcdMm = [double]::NaN, [double]$HoleDiameterMm = [double]::NaN,
    [double]$PlateWidthMm = [double]::NaN, [double]$PlateHeightMm = [double]::NaN,
    [double]$MotorHoleXMm = [double]::NaN, [double]$MotorHoleYMm = [double]::NaN,
    [double]$BearingOuterDiameterMm = [double]::NaN, [double]$RecessDepthMm = [double]::NaN,
    [string]$Manifest = '', [string]$Mate = '', [double]$DistanceMm = 0, [double]$DistanceMinMm = [double]::NaN, [double]$DistanceMaxMm = [double]::NaN, [double]$AngleDeg = 0, [double]$AngleMinDeg = [double]::NaN, [double]$AngleMaxDeg = [double]::NaN, [double]$GearRatioNumerator = 1, [double]$GearRatioDenominator = 1, [int]$SlotConstraintType = 0, [double]$SlotDistanceMm = [double]::NaN, [double]$SlotPercent = [double]::NaN, [switch]$Flip,
    [string]$SessionName = 'session', [string]$FromReport = '', [string]$OutDir = '',
    [string]$Message = '', [string]$Next = '', [string[]]$Artifact = @(),
    [string[]]$AllowDimension = @(), [string[]]$AllowComponent = @(), [string[]]$AllowComponentAdded = @(), [string[]]$AllowComponentRemoved = @(), [string[]]$AllowFeatureType = @(),
    [switch]$RequireAllowedChange, [switch]$ContractOnly, [switch]$ValidateOnly, [switch]$CleanupStale, [switch]$FullConsoleJson
)

$Root = Split-Path -Parent $PSCommandPath
$Workspace = Split-Path -Parent (Split-Path -Parent $Root)
function DefaultOut([string]$Name) { return (Join-Path $Workspace "tools/solidworks_codex/reports/$Name") }
function Expand-List([string[]]$Items) {
    $result = @()
    foreach ($item in $Items) {
        if ($null -eq $item) { continue }
        foreach ($part in ([string]$item -split ',')) {
            $trimmed = $part.Trim()
            if ($trimmed) { $result += $trimmed }
        }
    }
    return $result
}
function Invoke-SwPython([object[]]$Arguments) {
    $candidates = @()
    if ($env:SWCODEX_PYTHON) { $candidates += ,@($env:SWCODEX_PYTHON) }
    $codexPython = Join-Path $env:USERPROFILE '.cache\codex-runtimes\codex-primary-runtime\dependencies\python\python.exe'
    if (Test-Path $codexPython) { $candidates += ,@($codexPython) }
    $candidates += @(@('py','-3.12'), @('py','-3'), @('python'), @('python3'))

    $scriptPath = if ($Arguments.Count -gt 0) { [string]$Arguments[0] } else { '' }
    $requiresPywin32 = $false
    if ($scriptPath -and (Test-Path $scriptPath)) {
        $head = Get-Content -LiteralPath $scriptPath -TotalCount 80 -ErrorAction SilentlyContinue
        $requiresPywin32 = ($head -match 'import pythoncom|win32com').Count -gt 0
    }

    foreach ($candidate in $candidates) {
        $exe = [string]$candidate[0]
        $prefix = @()
        if ($candidate.Count -gt 1) { $prefix = $candidate[1..($candidate.Count - 1)] }
        & $exe @prefix -c "import sys; print(sys.executable)" *> $null
        if ($LASTEXITCODE -ne 0) { continue }
        if ($requiresPywin32) {
            & $exe @prefix -c "import pythoncom, win32com.client" *> $null
            if ($LASTEXITCODE -ne 0) { continue }
        }
        & $exe @prefix @Arguments | ForEach-Object { Write-Host $_ }
        $code = $LASTEXITCODE
        if ($null -eq $code) { return 0 }
        return [int]$code
    }
    if ($requiresPywin32) {
        Write-Error "No usable Python with pywin32 found. Install pywin32 or set SWCODEX_PYTHON to a python.exe path that can import pythoncom and win32com.client."
    } else {
        Write-Error "No usable Python found. Install Python 3 or set SWCODEX_PYTHON to a python.exe path."
    }
    return 127
}

switch ($Command) {
    'probe' { $outPath = if ($Out) { $Out } else { DefaultOut 'com_probe.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_com_probe.py'), '--out', $outPath)) }
    'start-probe' { $outPath = if ($Out) { $Out } else { DefaultOut 'com_probe_start.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_com_probe.py'), '--start', '--out', $outPath)) }
    'inspect' { $outPath = if ($Out) { $Out } else { DefaultOut 'assembly_inspect.json' }; $argsList = @((Join-Path $Root 'scripts/sw_assembly_inspect.py'), '--out', $outPath); if ($Model) { $argsList += @('--model', $Model) }; exit (Invoke-SwPython $argsList) }
    'start-inspect' { $outPath = if ($Out) { $Out } else { DefaultOut 'assembly_inspect_start.json' }; $argsList = @((Join-Path $Root 'scripts/sw_assembly_inspect.py'), '--start', '--out', $outPath); if ($Model) { $argsList += @('--model', $Model) }; exit (Invoke-SwPython $argsList) }
    'session-snapshot' { $argsList = @((Join-Path $Root 'scripts/sw_session_snapshot.py'), '--name', $SessionName, '--out-dir', $OutDir); if ($FromReport) { $argsList += @('--from-report', $FromReport) }; exit (Invoke-SwPython $argsList) }
    'start-session-snapshot' { $argsList = @((Join-Path $Root 'scripts/sw_session_snapshot.py'), '--start', '--name', $SessionName, '--out-dir', $OutDir); if ($FromReport) { $argsList += @('--from-report', $FromReport) }; exit (Invoke-SwPython $argsList) }
    'selection-report' { $outPath = if ($Out) { $Out } else { DefaultOut 'selection_report.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_selection_report.py'), '--out', $outPath)) }
    'start-selection-report' { $outPath = if ($Out) { $Out } else { DefaultOut 'selection_report_start.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_selection_report.py'), '--start', '--out', $outPath)) }
    'summary' { if (-not $Report) { throw 'summary requires -Report <json report path>' }; $argsList = @((Join-Path $Root 'scripts/sw_report_summary.py'), $Report); if ($Out) { $argsList += @('--out', $Out) }; exit (Invoke-SwPython $argsList) }
    'issue-report' { if (-not $Report) { throw 'issue-report requires -Report <inspect json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'issue_report.md' }; $argsList = @((Join-Path $Root 'scripts/sw_issue_report.py'), '--report', $Report, '--out', $outPath); if ($JsonOut) { $argsList += @('--json-out', $JsonOut) }; exit (Invoke-SwPython $argsList) }
    'compare' { if (-not $Before -or -not $After) { throw 'compare requires -Before and -After' }; $outPath = if ($Out) { $Out } else { DefaultOut 'report_delta.md' }; $argsList = @((Join-Path $Root 'scripts/sw_compare_reports.py'), '--before', $Before, '--after', $After, '--out', $outPath); if ($JsonOut) { $argsList += @('--json-out', $JsonOut) }; exit (Invoke-SwPython $argsList) }
    'change-verify' { if (-not $Report) { throw 'change-verify requires -Report <compare delta json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'change_verify.json' }; $argsList = @((Join-Path $Root 'scripts/sw_change_verify.py'), '--delta', $Report, '--out', $outPath); foreach ($x in (Expand-List $AllowDimension)) { $argsList += @('--allow-dimension', $x) }; foreach ($x in (Expand-List $AllowComponent)) { $argsList += @('--allow-component', $x) }; foreach ($x in (Expand-List $AllowComponentAdded)) { $argsList += @('--allow-component-added', $x) }; foreach ($x in (Expand-List $AllowComponentRemoved)) { $argsList += @('--allow-component-removed', $x) }; foreach ($x in (Expand-List $AllowFeatureType)) { $argsList += @('--allow-feature-type', $x) }; if ($RequireAllowedChange) { $argsList += '--require-allowed-change' }; exit (Invoke-SwPython $argsList) }
    'assembly-contract' { if (-not $Report) { throw 'assembly-contract requires -Report <inspect json>' }; if (-not $Manifest) { throw 'assembly-contract requires -Manifest <contract json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'assembly_contract.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_assembly_contract.py'), '--report', $Report, '--contract', $Manifest, '--out', $outPath)) }
    'part-geometry-validate' { if (-not $Report) { throw 'part-geometry-validate requires -Report <inspect json>' }; if (-not $Manifest) { throw 'part-geometry-validate requires -Manifest <geometry contract json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'part_geometry_validation.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_part_geometry_validate.py'), '--report', $Report, '--contract', $Manifest, '--out', $outPath)) }
    'visual-validate' { if (-not $Report) { throw 'visual-validate requires -Report <inspect json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'visual_validation.json' }; $argsList = @((Join-Path $Root 'scripts/sw_visual_validate.py'), '--report', $Report, '--out', $outPath); foreach ($file in $Files) { $argsList += @('--screenshot', $file) }; if ($Manifest) { $argsList += @('--visual-review', $Manifest) }; exit (Invoke-SwPython $argsList) }
    'motion-sweep-lite' { if (-not $Report) { throw 'motion-sweep-lite requires -Report <motion sweep spec json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'motion_sweep_lite.json' }; $argsList = @((Join-Path $Root 'scripts/sw_motion_sweep_lite.py'), '--spec', $Report, '--out', $outPath); if ($Manifest) { $argsList += @('--macro-manifest', $Manifest) }; if ($Model) { $argsList += @('--model', $Model) }; if ($ValidateOnly) { $argsList += '--dry-run' }; exit (Invoke-SwPython $argsList) }
    'engineering-lite' { if (-not $Report) { throw 'engineering-lite requires -Report <inspect json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'engineering_lite.md' }; $jsonTarget = if ($JsonOut) { $JsonOut } else { DefaultOut 'engineering_lite.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_engineering_lite.py'), '--report', $Report, '--out', $outPath, '--json-out', $jsonTarget)) }
    'backup' { if (-not $Files -or $Files.Count -eq 0) { throw 'backup requires -Files <file1,file2,...>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'backup.json' }; $argsList = @((Join-Path $Root 'scripts/sw_backup.py')) + $Files + @('--out', $outPath); exit (Invoke-SwPython $argsList) }
    'backup-status' { if (-not $Report) { throw 'backup-status requires -Report <backup json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'backup_status.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_backup_status.py'), '--report', $Report, '--out', $outPath)) }
    'restore-backup' { if (-not $Report) { throw 'restore-backup requires -Report <backup json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'restore_backup.json' }; $argsList = @((Join-Path $Root 'scripts/sw_restore_backup.py'), '--report', $Report, '--out', $outPath); if ($Apply) { $argsList += '--apply' }; exit (Invoke-SwPython $argsList) }
    'set-dimension' { if (-not $Dimension) { throw 'set-dimension requires -Dimension <full dimension name>' }; if ([double]::IsNaN($ValueM)) { throw 'set-dimension requires -ValueM <meters>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'set_dimension.json' }; $argsList = @((Join-Path $Root 'scripts/sw_set_dimension.py'), '--dimension', $Dimension, '--value-m', $ValueM, '--out', $outPath); if ($Model) { $argsList += @('--model', $Model) }; if ($Save) { $argsList += '--save' }; exit (Invoke-SwPython $argsList) }
    'safe-set-dimension' { if (-not $Model) { throw 'safe-set-dimension requires -Model <SolidWorks file>' }; if (-not $Dimension) { throw 'safe-set-dimension requires -Dimension <full dimension name>' }; if ([double]::IsNaN($ValueM)) { throw 'safe-set-dimension requires -ValueM <meters>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'safe_set_dimension.json' }; $artifactsDir = if ($OutDir) { $OutDir } else { 'tools/solidworks_codex/reports/safe_set_dimension' }; $argsList = @((Join-Path $Root 'scripts/sw_safe_set_dimension.py'), '--model', $Model, '--dimension', $Dimension, '--value-m', $ValueM, '--out-dir', $artifactsDir, '--out', $outPath); if ($Save) { $argsList += '--save' }; exit (Invoke-SwPython $argsList) }
    'rebuild' { $outPath = if ($Out) { $Out } else { DefaultOut 'rebuild.json' }; $argsList = @((Join-Path $Root 'scripts/sw_rebuild.py'), '--out', $outPath); if ($Model) { $argsList += @('--model', $Model) }; if ($Save) { $argsList += '--save' }; exit (Invoke-SwPython $argsList) }
    'start-rebuild' { $outPath = if ($Out) { $Out } else { DefaultOut 'rebuild_start.json' }; $argsList = @((Join-Path $Root 'scripts/sw_rebuild.py'), '--start', '--out', $outPath); if ($Model) { $argsList += @('--model', $Model) }; if ($Save) { $argsList += '--save' }; exit (Invoke-SwPython $argsList) }
    'export' { if (-not $Target) { throw 'export requires -Target <path>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'export.json' }; $argsList = @((Join-Path $Root 'scripts/sw_export.py'), '--target', $Target, '--out', $outPath); if ($Model) { $argsList += @('--model', $Model) }; exit (Invoke-SwPython $argsList) }
    'mass' { $outPath = if ($Out) { $Out } else { DefaultOut 'mass_properties.json' }; $argsList = @((Join-Path $Root 'scripts/sw_mass_properties.py'), '--out', $outPath); if ($Model) { $argsList += @('--model', $Model) }; exit (Invoke-SwPython $argsList) }
    'start-mass' { $outPath = if ($Out) { $Out } else { DefaultOut 'mass_properties_start.json' }; $argsList = @((Join-Path $Root 'scripts/sw_mass_properties.py'), '--start', '--out', $outPath); if ($Model) { $argsList += @('--model', $Model) }; exit (Invoke-SwPython $argsList) }
    'component-state' { if (-not $Component -or -not $Action) { throw 'component-state requires -Component and -Action' }; $outPath = if ($Out) { $Out } else { DefaultOut 'component_state.json' }; $argsList = @((Join-Path $Root 'scripts/sw_component_state.py'), '--component', $Component, '--action', $Action, '--out', $outPath); if ($Save) { $argsList += '--save' }; exit (Invoke-SwPython $argsList) }
    'start-component-state' { if (-not $Component -or -not $Action) { throw 'start-component-state requires -Component and -Action' }; $outPath = if ($Out) { $Out } else { DefaultOut 'component_state_start.json' }; $argsList = @((Join-Path $Root 'scripts/sw_component_state.py'), '--start', '--component', $Component, '--action', $Action, '--out', $outPath); if ($Save) { $argsList += '--save' }; exit (Invoke-SwPython $argsList) }
    'component-insert' { if (-not $Report) { throw 'component-insert requires -Report <component insert spec json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'component_insert.json' }; $argsList = @((Join-Path $Root 'scripts/sw_component_insert.py'), '--spec', $Report, '--out', $outPath); if ($Model) { $argsList += @('--model', $Model) }; if ($ValidateOnly) { $argsList += '--dry-run' }; if ($Save) { $argsList += '--save' }; exit (Invoke-SwPython $argsList) }
    'start-component-insert' { if (-not $Report) { throw 'start-component-insert requires -Report <component insert spec json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'component_insert_start.json' }; $argsList = @((Join-Path $Root 'scripts/sw_component_insert.py'), '--start', '--spec', $Report, '--out', $outPath); if ($Model) { $argsList += @('--model', $Model) }; if ($ValidateOnly) { $argsList += '--dry-run' }; if ($Save) { $argsList += '--save' }; exit (Invoke-SwPython $argsList) }
    'feature-state' { if (-not $Target -or -not $Action) { throw 'feature-state requires -Target <feature name> and -Action' }; $outPath = if ($Out) { $Out } else { DefaultOut 'feature_state.json' }; $argsList = @((Join-Path $Root 'scripts/sw_feature_state.py'), '--feature', $Target, '--action', $Action, '--out', $outPath); if ($Dimension) { $argsList += @('--dimension', $Dimension) }; if (-not [double]::IsNaN($ValueM)) { $argsList += @('--value-m', $ValueM) }; if ($TargetFeature) { $argsList += @('--target-feature', $TargetFeature) }; if ($ReorderPosition) { $argsList += @('--reorder-position', $ReorderPosition) }; if ($Model) { $argsList += @('--model', $Model) }; if ($Save) { $argsList += '--save' }; exit (Invoke-SwPython $argsList) }
    'start-feature-state' { if (-not $Target -or -not $Action) { throw 'start-feature-state requires -Target <feature name> and -Action' }; $outPath = if ($Out) { $Out } else { DefaultOut 'feature_state_start.json' }; $argsList = @((Join-Path $Root 'scripts/sw_feature_state.py'), '--start', '--feature', $Target, '--action', $Action, '--out', $outPath); if ($Dimension) { $argsList += @('--dimension', $Dimension) }; if (-not [double]::IsNaN($ValueM)) { $argsList += @('--value-m', $ValueM) }; if ($TargetFeature) { $argsList += @('--target-feature', $TargetFeature) }; if ($ReorderPosition) { $argsList += @('--reorder-position', $ReorderPosition) }; if ($Model) { $argsList += @('--model', $Model) }; if ($Save) { $argsList += '--save' }; exit (Invoke-SwPython $argsList) }
    'part-feature-execute' { if (-not $Report) { throw 'part-feature-execute requires -Report <part feature spec json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'part_feature_execute.json' }; $argsList = @((Join-Path $Root 'scripts/sw_part_feature_execute.py'), '--spec', $Report, '--out', $outPath); if ($Model) { $argsList += @('--model', $Model) }; if ($ValidateOnly) { $argsList += '--dry-run' }; if ($Save) { $argsList += '--save' }; exit (Invoke-SwPython $argsList) }
    'start-part-feature-execute' { if (-not $Report) { throw 'start-part-feature-execute requires -Report <part feature spec json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'part_feature_execute_start.json' }; $argsList = @((Join-Path $Root 'scripts/sw_part_feature_execute.py'), '--start', '--spec', $Report, '--out', $outPath); if ($Model) { $argsList += @('--model', $Model) }; if ($ValidateOnly) { $argsList += '--dry-run' }; if ($Save) { $argsList += '--save' }; exit (Invoke-SwPython $argsList) }
    'metadata-execute' { if (-not $Report) { throw 'metadata-execute requires -Report <metadata spec json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'metadata_execute.json' }; $argsList = @((Join-Path $Root 'scripts/sw_metadata_execute.py'), '--spec', $Report, '--out', $outPath); if ($Model) { $argsList += @('--model', $Model) }; if ($ValidateOnly) { $argsList += '--dry-run' }; if ($Save) { $argsList += '--save' }; exit (Invoke-SwPython $argsList) }
    'start-metadata-execute' { if (-not $Report) { throw 'start-metadata-execute requires -Report <metadata spec json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'metadata_execute_start.json' }; $argsList = @((Join-Path $Root 'scripts/sw_metadata_execute.py'), '--start', '--spec', $Report, '--out', $outPath); if ($Model) { $argsList += @('--model', $Model) }; if ($ValidateOnly) { $argsList += '--dry-run' }; if ($Save) { $argsList += '--save' }; exit (Invoke-SwPython $argsList) }
    'interference' { $outPath = if ($Out) { $Out } else { DefaultOut 'interference.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_interference.py'), '--out', $outPath)) }
    'start-interference' { $outPath = if ($Out) { $Out } else { DefaultOut 'interference_start.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_interference.py'), '--start', '--out', $outPath)) }
    'template-macro' { if (-not $Template) { throw 'template-macro requires -Template sleeve|spacer|flange|endcap|motor_adapter|bearing_retainer' }; $outPath = if ($Out) { $Out } else { "tools/solidworks_codex/macros/$Template.swp.vba" }; $manifestPath = if ($Manifest) { $Manifest } else { DefaultOut "${Template}_manifest.json" }; $argsList = @((Join-Path $Root 'scripts/sw_template_macro.py'), '--template', $Template, '--out', $outPath, '--manifest', $manifestPath); if (-not [double]::IsNaN($OuterDiameterMm)) { $argsList += @('--outer-diameter-mm', $OuterDiameterMm) }; if (-not [double]::IsNaN($InnerDiameterMm)) { $argsList += @('--inner-diameter-mm', $InnerDiameterMm) }; if (-not [double]::IsNaN($LengthMm)) { $argsList += @('--length-mm', $LengthMm) }; if (-not [double]::IsNaN($ThicknessMm)) { $argsList += @('--thickness-mm', $ThicknessMm) }; if (-not [double]::IsNaN($CenterBoreMm)) { $argsList += @('--center-bore-mm', $CenterBoreMm) }; if ($HoleCount -ge 0) { $argsList += @('--hole-count', $HoleCount) }; if (-not [double]::IsNaN($HolePcdMm)) { $argsList += @('--hole-pcd-mm', $HolePcdMm) }; if (-not [double]::IsNaN($HoleDiameterMm)) { $argsList += @('--hole-diameter-mm', $HoleDiameterMm) }; if (-not [double]::IsNaN($PlateWidthMm)) { $argsList += @('--plate-width-mm', $PlateWidthMm) }; if (-not [double]::IsNaN($PlateHeightMm)) { $argsList += @('--plate-height-mm', $PlateHeightMm) }; if (-not [double]::IsNaN($MotorHoleXMm)) { $argsList += @('--motor-hole-x-mm', $MotorHoleXMm) }; if (-not [double]::IsNaN($MotorHoleYMm)) { $argsList += @('--motor-hole-y-mm', $MotorHoleYMm) }; if (-not [double]::IsNaN($BearingOuterDiameterMm)) { $argsList += @('--bearing-outer-diameter-mm', $BearingOuterDiameterMm) }; if (-not [double]::IsNaN($RecessDepthMm)) { $argsList += @('--recess-depth-mm', $RecessDepthMm) }; exit (Invoke-SwPython $argsList) }
    'mate-macro' { if (-not $Mate) { throw 'mate-macro requires -Mate coincident|concentric|tangent|distance|limit_distance|angle|limit_angle|parallel|perpendicular|symmetry|cam|cam_follower|gear|path|slot' }; $outPath = if ($Out) { $Out } else { "tools/solidworks_codex/macros/mate_${Mate}_preselect.swp.vba" }; $manifestPath = if ($Manifest) { $Manifest } else { DefaultOut "mate_${Mate}_manifest.json" }; $argsList = @((Join-Path $Root 'scripts/sw_mate_macro.py'), '--mate', $Mate, '--distance-mm', $DistanceMm, '--angle-deg', $AngleDeg, '--gear-ratio-numerator', $GearRatioNumerator, '--gear-ratio-denominator', $GearRatioDenominator, '--slot-constraint-type', $SlotConstraintType, '--out', $outPath, '--manifest', $manifestPath); if (-not [double]::IsNaN($DistanceMinMm)) { $argsList += @('--distance-min-mm', $DistanceMinMm) }; if (-not [double]::IsNaN($DistanceMaxMm)) { $argsList += @('--distance-max-mm', $DistanceMaxMm) }; if (-not [double]::IsNaN($AngleMinDeg)) { $argsList += @('--angle-min-deg', $AngleMinDeg) }; if (-not [double]::IsNaN($AngleMaxDeg)) { $argsList += @('--angle-max-deg', $AngleMaxDeg) }; if (-not [double]::IsNaN($SlotDistanceMm)) { $argsList += @('--slot-distance-mm', $SlotDistanceMm) }; if (-not [double]::IsNaN($SlotPercent)) { $argsList += @('--slot-percent', $SlotPercent) }; if ($Flip) { $argsList += '--flip' }; exit (Invoke-SwPython $argsList) }
    'mate-group-macro' { if (-not $Report) { throw 'mate-group-macro requires -Report <mate group plan json>' }; $macroDir = if ($OutDir) { $OutDir } else { 'tools/solidworks_codex/macros/mate_groups' }; $manifestPath = if ($Out) { $Out } else { DefaultOut 'mate_group_macro_manifest.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_mate_group_macro.py'), '--mate-group-plan', $Report, '--out-dir', $macroDir, '--manifest', $manifestPath)) }
    'mate-group-execute' { if (-not $Report) { throw 'mate-group-execute requires -Report <mate group macro manifest json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'mate_group_execute.json' }; $argsList = @((Join-Path $Root 'scripts/sw_mate_group_execute.py'), '--macro-manifest', $Report, '--out', $outPath); if ($ValidateOnly) { $argsList += '--dry-run' }; exit (Invoke-SwPython $argsList) }
    'preflight' { $outPath = if ($Out) { $Out } else { DefaultOut 'preflight.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_preflight.py'), '--out', $outPath)) }
    'design-review' { if (-not $Report) { throw 'design-review requires -Report <inspect json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'design_review.md' }; $jsonTarget = if ($JsonOut) { $JsonOut } else { DefaultOut 'design_review.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_design_review.py'), '--report', $Report, '--intent', $Target, '--out', $outPath, '--json-out', $jsonTarget)) }
    'change-plan' { if (-not $Report) { throw 'change-plan requires -Report <inspect json>' }; if (-not $Target) { throw 'change-plan requires -Target <change goal text>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'change_plan.md' }; $jsonTarget = if ($JsonOut) { $JsonOut } else { DefaultOut 'change_plan.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_change_plan.py'), '--report', $Report, '--goal', $Target, '--session-name', $SessionName, '--out', $outPath, '--json-out', $jsonTarget)) }
    'workflow-plan' { if (-not $Target) { throw 'workflow-plan requires -Target <workflow goal text>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'workflow_plan.md' }; $jsonTarget = if ($JsonOut) { $JsonOut } else { DefaultOut 'workflow_plan.json' }; $intent = if ($Action) { $Action } else { 'auto' }; $budget = if ($View -and $View -ne 'auto') { $View } else { 'standard' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_workflow_plan.py'), '--goal', $Target, '--intent', $intent, '--runtime-budget', $budget, '--out', $outPath, '--json-out', $jsonTarget)) }
    'report-search' { if (-not $Report) { throw 'report-search requires -Report <inspect json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'report_search.md' }; $jsonTarget = if ($JsonOut) { $JsonOut } else { DefaultOut 'report_search.json' }; $kind = if ($Action) { $Action } else { 'all' }; $state = if ($Component) { $Component } else { 'any' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_report_search.py'), '--report', $Report, '--query', $Target, '--kind', $kind, '--state', $state, '--out', $outPath, '--json-out', $jsonTarget)) }
    'report-context' { if (-not $Report) { throw 'report-context requires -Report <inspect json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'report_context.md' }; $jsonTarget = if ($JsonOut) { $JsonOut } else { DefaultOut 'report_context.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_report_context.py'), '--report', $Report, '--focus', $Target, '--out', $outPath, '--json-out', $jsonTarget)) }
    'model-understand' { if (-not $Report) { throw 'model-understand requires -Report <inspect json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'model_understanding.md' }; $jsonTarget = if ($JsonOut) { $JsonOut } else { DefaultOut 'model_understanding.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_model_understand.py'), '--report', $Report, '--task', $Target, '--view', $View, '--out', $outPath, '--json-out', $jsonTarget)) }
    'assembly-diagnose' { if (-not $Report) { throw 'assembly-diagnose requires -Report <inspect json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'assembly_diagnosis.json' }; $argsList = @((Join-Path $Root 'scripts/sw_assembly_diagnose.py'), '--report', $Report, '--out', $outPath); if ($OutDir) { $argsList += @('--lock-root', $OutDir) }; if ($DistanceMm -gt 0) { $argsList += @('--near-tolerance-m', ($DistanceMm / 1000.0)) }; if ($Target) { $argsList += @('--standard-part-regex', $Target) }; exit (Invoke-SwPython $argsList) }
    'assembly-repair-plan' { if (-not $Report) { throw 'assembly-repair-plan requires -Report <assembly diagnosis json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'assembly_repair_plan.json' }; $mdPath = if ($JsonOut) { $JsonOut } else { DefaultOut 'assembly_repair_plan.md' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_assembly_repair_plan.py'), '--diagnosis', $Report, '--out', $outPath, '--markdown-out', $mdPath)) }
    'interface-index' { if (-not $Report) { throw 'interface-index requires -Report <inspect json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'interface_index.json' }; $argsList = @((Join-Path $Root 'scripts/sw_interface_index.py'), '--report', $Report, '--out', $outPath); if ($DistanceMm -gt 0) { $argsList += @('--near-tolerance-m', ($DistanceMm / 1000.0)) }; if ($Target) { $argsList += @('--standard-part-regex', $Target) }; exit (Invoke-SwPython $argsList) }
    'mate-group-plan' { if (-not $Report) { throw 'mate-group-plan requires -Report <assembly repair plan json>' }; if (-not $FromReport) { throw 'mate-group-plan requires -FromReport <interface index json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'mate_group_plan.json' }; $mdPath = if ($JsonOut) { $JsonOut } else { DefaultOut 'mate_group_plan.md' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_mate_group_plan.py'), '--repair-plan', $Report, '--interface-index', $FromReport, '--out', $outPath, '--markdown-out', $mdPath)) }
    'mate-group-validate' { if (-not $Report) { throw 'mate-group-validate requires -Report <mate group plan json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'mate_group_validation.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_mate_group_validate.py'), '--mate-group-plan', $Report, '--out', $outPath)) }
    'mate-selection-check' { if (-not $Report) { throw 'mate-selection-check requires -Report <mate group macro manifest json>' }; if (-not $FromReport) { throw 'mate-selection-check requires -FromReport <selection report json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'mate_selection_check.json' }; $argsList = @((Join-Path $Root 'scripts/sw_mate_selection_check.py'), '--macro-manifest', $Report, '--selection-report', $FromReport, '--out', $outPath); if ($Mate) { $argsList += @('--expected-mate-name', $Mate) }; exit (Invoke-SwPython $argsList) }
    'mate-group-execution-check' { if (-not $Report) { throw 'mate-group-execution-check requires -Report <mate group macro manifest json>' }; if (-not $After) { throw 'mate-group-execution-check requires -After <after inspect json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'mate_group_execution_check.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_mate_group_execution_check.py'), '--macro-manifest', $Report, '--after-report', $After, '--out', $outPath)) }
    'mate-group-live-protocol' { if (-not $Report) { throw 'mate-group-live-protocol requires -Report <mate group macro manifest json>' }; if (-not $FromReport) { throw 'mate-group-live-protocol requires -FromReport <mate group validation json>' }; $outPath = if ($Out) { $Out } else { DefaultOut 'mate_group_live_protocol.json' }; $mdPath = if ($JsonOut) { $JsonOut } else { DefaultOut 'mate_group_live_protocol.md' }; $argsList = @((Join-Path $Root 'scripts/sw_mate_group_live_protocol.py'), '--macro-manifest', $Report, '--validation-report', $FromReport, '--out', $outPath, '--markdown-out', $mdPath); if ($Model) { $argsList += @('--model', $Model) }; exit (Invoke-SwPython $argsList) }
    'assembly-review-pipeline' { if (-not $Report) { throw 'assembly-review-pipeline requires -Report <inspect json>' }; $reviewDir = if ($OutDir) { $OutDir } else { 'tools/solidworks_codex/reports/assembly_review' }; $argsList = @((Join-Path $Root 'scripts/sw_assembly_review_pipeline.py'), '--report', $Report, '--out-dir', $reviewDir); if ($DistanceMm -gt 0) { $argsList += @('--near-tolerance-m', ($DistanceMm / 1000.0)) }; if ($Target) { $argsList += @('--standard-part-regex', $Target) }; exit (Invoke-SwPython $argsList) }
    'worklog' { if (-not $Message) { throw 'worklog requires -Message <text>' }; $logPath = if ($Out) { $Out } else { DefaultOut 'worklog.jsonl' }; $summaryPath = if ($JsonOut) { $JsonOut } else { DefaultOut 'worklog.md' }; $eventName = if ($Action) { $Action } else { 'note' }; $argsList = @((Join-Path $Root 'scripts/sw_worklog.py'), '--log', $logPath, '--summary-out', $summaryPath, '--session', $SessionName, '--event', $eventName, '--message', $Message); foreach ($a in $Artifact) { $argsList += @('--artifact', $a) }; if ($Next) { $argsList += @('--next', $Next) }; exit (Invoke-SwPython $argsList) }
    'handoff-bundle' { if (-not $Report) { throw 'handoff-bundle requires -Report <inspect json>' }; $bundleDir = if ($OutDir) { $OutDir } else { 'tools/solidworks_codex/reports/handoff' }; $worklogPath = if ($FromReport) { $FromReport } else { DefaultOut 'worklog.jsonl' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_handoff_bundle.py'), '--report', $Report, '--worklog', $worklogPath, '--focus', $Target, '--out-dir', $bundleDir)) }
    'tool-catalog' { $outPath = if ($Out) { $Out } else { DefaultOut 'tool_catalog.md' }; $jsonTarget = if ($JsonOut) { $JsonOut } else { DefaultOut 'tool_catalog.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_tool_catalog.py'), '--out', $outPath, '--json-out', $jsonTarget)) }
    'offline-demo' { $demoDir = if ($OutDir) { $OutDir } else { 'docs/demo/offline' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_offline_demo.py'), '--out-dir', $demoDir)) }
    'public-copy-guard' { $outPath = if ($Out) { $Out } else { DefaultOut 'public_copy_guard.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_public_copy_guard.py'), '--out', $outPath)) }
    'github-readiness' { $outPath = if ($Out) { $Out } else { DefaultOut 'github_readiness.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_github_readiness.py'), '--out', $outPath)) }
    'repo-health' { $outPath = if ($Out) { $Out } else { DefaultOut 'repo_health.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_repo_health.py'), '--out', $outPath)) }
    'release-tree' { $outPath = if ($Out) { $Out } else { DefaultOut 'release_tree.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_release_tree.py'), '--out', $outPath)) }
    'capability-matrix' { $outPath = if ($Out) { $Out } else { 'docs/capability-matrix.md' }; $jsonTarget = if ($JsonOut) { $JsonOut } else { 'docs/capability-matrix.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_capability_matrix.py'), '--out', $outPath, '--json-out', $jsonTarget)) }
    'live-gate' { $outPath = if ($Out) { $Out } else { DefaultOut 'live_validation_gate.json' }; $argsList = @((Join-Path $Root 'scripts/sw_live_validation_gate.py'), '--out', $outPath); if ($ContractOnly) { $argsList += '--contract-only' }; if ($ValidateOnly) { $argsList += '--validate-only' }; if ($CleanupStale) { $argsList += '--cleanup-stale' }; if ($FullConsoleJson) { $argsList += '--full-console-json' }; exit (Invoke-SwPython $argsList) }
    'finalize' { $outPath = if ($Out) { $Out } else { 'docs/solidworks-codex-final-readiness.md' }; $jsonTarget = if ($JsonOut) { $JsonOut } else { DefaultOut 'final_readiness.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_finalize.py'), '--run-audit', '--out', $outPath, '--json-out', $jsonTarget)) }
    'audit' { $outPath = if ($Out) { $Out } else { DefaultOut 'audit_latest.json' }; exit (Invoke-SwPython @((Join-Path $Root 'scripts/sw_audit.py'), '--out', $outPath)) }
    'mcp-tools' { Push-Location $Workspace; try { node (Join-Path $Workspace 'tools/mcp-solidworks-ts/list-tools.cjs'); $code = $LASTEXITCODE } finally { Pop-Location }; exit $code }
}
