#!/usr/bin/env node
// Minimal MCP stdio server wrapping tools/solidworks_codex/swctl.ps1.
// It intentionally exposes a narrow, conservative tool surface: read-only inspect/probe,
// explicit backup, dimension update, and MCP tool enumeration.

const { spawn } = require('node:child_process');
const path = require('node:path');

const workspace = path.resolve(__dirname, '..', '..', '..');
const swctl = path.join(workspace, 'tools', 'solidworks_codex', 'swctl.ps1');

let buffer = '';
let shuttingDown = false;

const toolSchemas = [
  {
    name: 'solidworks_probe',
    description: 'Read-only attach to an already-running SolidWorks instance and summarize active document.',
    inputSchema: {
      type: 'object',
      properties: {
        out: { type: 'string', description: 'Optional output JSON path.' }
      },
      additionalProperties: false
    }
  },
  {
    name: 'solidworks_start_probe',
    description: 'Allow COM launch of SolidWorks, then summarize active document.',
    inputSchema: {
      type: 'object',
      properties: {
        out: { type: 'string', description: 'Optional output JSON path.' }
      },
      additionalProperties: false
    }
  },
  {
    name: 'solidworks_inspect',
    description: 'Deep read-only inspect of active part/assembly: features, dimensions, components.',
    inputSchema: {
      type: 'object',
      properties: {
        model: { type: 'string', description: 'Optional SolidWorks file to open before inspection.' },
        out: { type: 'string', description: 'Optional output JSON path.' }
      },
      additionalProperties: false
    }
  },
  {
    name: 'solidworks_start_inspect',
    description: 'Allow COM launch of SolidWorks, then run deep read-only inspect.',
    inputSchema: {
      type: 'object',
      properties: {
        model: { type: 'string', description: 'Optional SolidWorks file to open before inspection.' },
        out: { type: 'string', description: 'Optional output JSON path.' }
      },
      additionalProperties: false
    }
  },
  {
    name: 'solidworks_backup',
    description: 'Create timestamped backups of .SLDPRT/.SLDASM/.SLDDRW files before modification.',
    inputSchema: {
      type: 'object',
      properties: {
        files: {
          type: 'array',
          items: { type: 'string' },
          minItems: 1,
          description: 'SolidWorks files to back up.'
        },
        out: { type: 'string', description: 'Optional report JSON path.' }
      },
      required: ['files'],
      additionalProperties: false
    }
  },
  {
    name: 'solidworks_backup_status',
    description: 'Inspect a backup report and classify source files as unchanged, changed, missing, or restorable.',
    inputSchema: {
      type: 'object',
      properties: {
        report: { type: 'string', description: 'Backup report JSON generated by solidworks_backup.' },
        out: { type: 'string', description: 'Optional status report JSON path.' }
      },
      required: ['report'],
      additionalProperties: false
    }
  },
  {
    name: 'solidworks_restore_backup',
    description: 'Dry-run or apply restoration from a SolidWorks Codex backup report. apply=false only validates and plans.',
    inputSchema: {
      type: 'object',
      properties: {
        report: { type: 'string', description: 'Backup report JSON generated by solidworks_backup.' },
        apply: { type: 'boolean', description: 'Actually overwrite source files with backups. Defaults to dry-run.' },
        out: { type: 'string', description: 'Optional restore report JSON path.' }
      },
      required: ['report'],
      additionalProperties: false
    }
  },
  {
    name: 'solidworks_set_dimension',
    description: 'Set one SolidWorks dimension by full parameter name. Value is SystemValue in meters. Use save only after backup.',
    inputSchema: {
      type: 'object',
      properties: {
        dimension: { type: 'string', description: 'Full SolidWorks dimension/parameter name.' },
        value_m: { type: 'number', description: 'New SystemValue in meters.' },
        model: { type: 'string', description: 'Optional model path to open.' },
        save: { type: 'boolean', description: 'Save after changing; backup first.' },
        out: { type: 'string', description: 'Optional report JSON path.' }
      },
      required: ['dimension', 'value_m'],
      additionalProperties: false
    }
  },
  {
    name: 'solidworks_safe_set_dimension',
    description: 'Run a guarded one-dimension edit pipeline: backup, inspect, set dimension, rebuild, inspect, compare, and verify only that dimension changed.',
    inputSchema: {
      type: 'object',
      properties: {
        model: { type: 'string', description: 'SolidWorks model file to back up and edit.' },
        dimension: { type: 'string', description: 'Full SolidWorks dimension/parameter name.' },
        value_m: { type: 'number', description: 'New SystemValue in meters.' },
        save: { type: 'boolean', description: 'Save during set/rebuild. Defaults to false.' },
        out_dir: { type: 'string', description: 'Directory for pipeline artifacts.' },
        out: { type: 'string', description: 'Optional pipeline report JSON path.' }
      },
      required: ['model', 'dimension', 'value_m'],
      additionalProperties: false
    }
  },
  {
    name: 'solidworks_rebuild',
    description: 'Rebuild active or specified SolidWorks document; optionally save.',
    inputSchema: { type: 'object', properties: { model: { type: 'string' }, save: { type: 'boolean' }, out: { type: 'string' } }, additionalProperties: false }
  },
  {
    name: 'solidworks_export',
    description: 'Export active or specified SolidWorks document to target path. Format follows suffix.',
    inputSchema: { type: 'object', properties: { model: { type: 'string' }, target: { type: 'string' }, out: { type: 'string' } }, required: ['target'], additionalProperties: false }
  },
  {
    name: 'solidworks_mass_properties',
    description: 'Report mass properties for active or specified SolidWorks document.',
    inputSchema: { type: 'object', properties: { model: { type: 'string' }, out: { type: 'string' } }, additionalProperties: false }
  },
  {
    name: 'solidworks_compare_reports',
    description: 'Compare two SolidWorks Codex inspect JSON reports.',
    inputSchema: { type: 'object', properties: { before: { type: 'string' }, after: { type: 'string' }, out: { type: 'string' }, json_out: { type: 'string' } }, required: ['before', 'after'], additionalProperties: false }
  },
  {
    name: 'solidworks_change_verify',
    description: 'Verify a compare delta contains only expected dimensions, component changes, additions/removals, or feature type count changes.',
    inputSchema: { type: 'object', properties: { delta: { type: 'string' }, allow_dimension: { type: 'array', items: { type: 'string' } }, allow_component: { type: 'array', items: { type: 'string' } }, allow_component_added: { type: 'array', items: { type: 'string' } }, allow_component_removed: { type: 'array', items: { type: 'string' } }, allow_feature_type: { type: 'array', items: { type: 'string' } }, require_allowed_change: { type: 'boolean', description: 'Fail if allow lists are provided but no allowed change is observed.' }, out: { type: 'string' } }, required: ['delta'], additionalProperties: false }
  },  {
    name: 'solidworks_component_state',
    description: 'Change assembly component state by Component2.Name2: hide/show/suppress/unsuppress/fix/float.',
    inputSchema: { type: 'object', properties: { component: { type: 'string' }, action: { type: 'string', enum: ['hide','show','suppress','unsuppress','fix','float'] }, save: { type: 'boolean' }, out: { type: 'string' } }, required: ['component','action'], additionalProperties: false }
  },
  {
    name: 'solidworks_feature_state',
    description: 'Change part or assembly feature state by feature name: suppress/unsuppress/delete, then rebuild and report before/after evidence.',
    inputSchema: { type: 'object', properties: { feature: { type: 'string' }, action: { type: 'string', enum: ['suppress','unsuppress','delete'] }, model: { type: 'string' }, save: { type: 'boolean' }, out: { type: 'string' } }, required: ['feature','action'], additionalProperties: false }
  },
  {
    name: 'solidworks_interference_check',
    description: 'Run conservative SolidWorks assembly interference detection and emit JSON.',
    inputSchema: { type: 'object', properties: { out: { type: 'string' } }, additionalProperties: false }
  },  {
    name: 'solidworks_template_macro',
    description: 'Generate reviewable VBA macro for common mechanical part templates such as sleeve, spacer, flange, endcap, adapter, and retainer.',
    inputSchema: { type: 'object', properties: { template: { type: 'string', enum: ['sleeve','spacer','flange','endcap','motor_adapter','bearing_retainer'] }, out: { type: 'string' }, manifest: { type: 'string' }, outer_diameter_mm: { type: 'number' }, inner_diameter_mm: { type: 'number' }, length_mm: { type: 'number' }, thickness_mm: { type: 'number' }, center_bore_mm: { type: 'number' }, hole_count: { type: 'integer' }, hole_pcd_mm: { type: 'number' }, hole_diameter_mm: { type: 'number' }, plate_width_mm: { type: 'number' }, plate_height_mm: { type: 'number' }, motor_hole_x_mm: { type: 'number' }, motor_hole_y_mm: { type: 'number' }, bearing_outer_diameter_mm: { type: 'number' }, recess_depth_mm: { type: 'number' } }, required: ['template'], additionalProperties: false }
  },  {
    name: 'solidworks_issue_report',
    description: 'Generate a practical issue/recommendation report from an inspect JSON report.',
    inputSchema: { type: 'object', properties: { report: { type: 'string' }, out: { type: 'string' }, json_out: { type: 'string' } }, required: ['report'], additionalProperties: false }
  },
  {
    name: 'solidworks_mate_macro',
    description: 'Generate reviewable VBA macro for adding a mate between two preselected entities.',
    inputSchema: { type: 'object', properties: { mate: { type: 'string', enum: ['coincident','concentric','tangent','distance','limit_distance','angle','limit_angle','parallel','perpendicular','symmetry'] }, distance_mm: { type: 'number' }, distance_min_mm: { type: 'number' }, distance_max_mm: { type: 'number' }, angle_deg: { type: 'number' }, angle_min_deg: { type: 'number' }, angle_max_deg: { type: 'number' }, flip: { type: 'boolean' }, out: { type: 'string' }, manifest: { type: 'string' } }, required: ['mate'], additionalProperties: false }
  },
  {
    name: 'solidworks_mate_group_macro',
    description: 'Generate reviewable preselect VBA macro drafts from a mate group plan. Each macro still requires live entity preselection and review before running.',
    inputSchema: { type: 'object', properties: { mate_group_plan: { type: 'string' }, out_dir: { type: 'string' }, manifest: { type: 'string' } }, required: ['mate_group_plan'], additionalProperties: false }
  },
  {
    name: 'solidworks_mate_group_execute',
    description: 'Execute reviewed mate group selector evidence in the active SolidWorks assembly using SelectByID2, AddMate5, and immediate rebuild. dry_run only plans selector actions.',
    inputSchema: { type: 'object', properties: { macro_manifest: { type: 'string' }, dry_run: { type: 'boolean' }, out: { type: 'string' } }, required: ['macro_manifest'], additionalProperties: false }
  },  {
    name: 'solidworks_selection_report',
    description: 'Report current SolidWorks selection set for safe preselected-entity mate workflows.',
    inputSchema: { type: 'object', properties: { out: { type: 'string' }, start: { type: 'boolean' } }, additionalProperties: false }
  },  {
    name: 'solidworks_session_snapshot',
    description: 'Create a work-session package: inspect JSON, summary Markdown, issue report, manifest.',
    inputSchema: { type: 'object', properties: { name: { type: 'string' }, from_report: { type: 'string' }, out_dir: { type: 'string' }, start: { type: 'boolean' } }, additionalProperties: false }
  },  {
    name: 'solidworks_report_summary',
    description: 'Summarize a SolidWorks Codex JSON probe/inspect report into Markdown.',
    inputSchema: {
      type: 'object',
      properties: {
        report: { type: 'string', description: 'JSON report path.' },
        out: { type: 'string', description: 'Optional Markdown output path.' }
      },
      required: ['report'],
      additionalProperties: false
    }
  },  {
    name: 'solidworks_design_review',
    description: 'Generate a generic evidence-first mechanical CAD review from an inspect JSON report: findings, open questions, and candidate actions.',
    inputSchema: { type: 'object', properties: { report: { type: 'string' }, intent: { type: 'string' }, out: { type: 'string' }, json_out: { type: 'string' } }, required: ['report'], additionalProperties: false }
  },
  {
    name: 'solidworks_change_plan',
    description: 'Generate a flexible evidence-first mechanical CAD change plan from an inspect JSON report and natural-language goal.',
    inputSchema: { type: 'object', properties: { report: { type: 'string' }, goal: { type: 'string' }, session_name: { type: 'string' }, out: { type: 'string' }, json_out: { type: 'string' } }, required: ['report','goal'], additionalProperties: false }
  },  {
    name: 'solidworks_report_search',
    description: 'Search an inspect JSON report for components, dimensions, and features by text/state when names are messy.',
    inputSchema: { type: 'object', properties: { report: { type: 'string' }, query: { type: 'string' }, kind: { type: 'string', enum: ['all','components','dimensions','features'] }, state: { type: 'string', enum: ['any','suppressed','unsuppressed','hidden','shown','fixed','floating','lightweight'] }, out: { type: 'string' }, json_out: { type: 'string' } }, required: ['report'], additionalProperties: false }
  },
  {
    name: 'solidworks_report_context',
    description: 'Build a freeform handoff/context pack from an inspect report: inventory, risks, anchors, and next commands.',
    inputSchema: { type: 'object', properties: { report: { type: 'string' }, focus: { type: 'string' }, out: { type: 'string' }, json_out: { type: 'string' } }, required: ['report'], additionalProperties: false }
  },
  {
    name: 'solidworks_model_understand',
    description: 'Build a compact task-scoped model understanding pack from an inspect report: baseline facts, relevant CAD objects, relationship hypotheses, risks, and next minimal queries.',
    inputSchema: { type: 'object', properties: { report: { type: 'string' }, task: { type: 'string' }, view: { type: 'string', enum: ['auto','general','dimension-edit','assembly-constraints','interference-clearance','manufacturing-holes','spatial-assembly'] }, out: { type: 'string' }, json_out: { type: 'string' } }, required: ['report'], additionalProperties: false }
  },
  {
    name: 'solidworks_assembly_diagnose',
    description: 'Diagnose an assembly inspect report: fixed/floating state, mate graph gaps, bad mates, isolated/no-mate components, bbox spacing, standard-part attachment, and lock-file hints.',
    inputSchema: { type: 'object', properties: { report: { type: 'string' }, out: { type: 'string' }, lock_root: { type: 'string' }, near_tolerance_m: { type: 'number' }, standard_part_regex: { type: 'string' } }, required: ['report'], additionalProperties: false }
  },
  {
    name: 'solidworks_assembly_repair_plan',
    description: 'Build a read-only local repair plan from an assembly diagnosis JSON: bad mate resolution order, hostless standard-part host suggestions, and isolated-component intent questions.',
    inputSchema: { type: 'object', properties: { diagnosis: { type: 'string' }, out: { type: 'string' }, markdown_out: { type: 'string' } }, required: ['diagnosis'], additionalProperties: false }
  },
  {
    name: 'solidworks_interface_index',
    description: 'Build a read-only heuristic component/interface index from an inspect report: bbox contact candidates, nearest neighbors, standard-part hints, and root/suppression role hints.',
    inputSchema: { type: 'object', properties: { report: { type: 'string' }, out: { type: 'string' }, near_tolerance_m: { type: 'number' }, standard_part_regex: { type: 'string' } }, required: ['report'], additionalProperties: false }
  },
  {
    name: 'solidworks_mate_group_plan',
    description: 'Build a read-only mate group plan from an assembly repair plan and interface index: grouped candidate mates, components, evidence, and per-group verification.',
    inputSchema: { type: 'object', properties: { repair_plan: { type: 'string' }, interface_index: { type: 'string' }, out: { type: 'string' }, markdown_out: { type: 'string' } }, required: ['repair_plan', 'interface_index'], additionalProperties: false }
  },
  {
    name: 'solidworks_mate_group_validate',
    description: 'Validate a read-only mate group plan before macro or live execution: component count, supported mate types, and required rebuild/mate-error verification.',
    inputSchema: { type: 'object', properties: { mate_group_plan: { type: 'string' }, out: { type: 'string' } }, required: ['mate_group_plan'], additionalProperties: false }
  },
  {
    name: 'solidworks_mate_selection_check',
    description: 'Validate current selection-report evidence against a mate macro manifest before running a reviewed mate macro: exactly two supported entity selections on expected components.',
    inputSchema: { type: 'object', properties: { macro_manifest: { type: 'string' }, selection_report: { type: 'string' }, expected_mate_name: { type: 'string' }, out: { type: 'string' } }, required: ['macro_manifest', 'selection_report'], additionalProperties: false }
  },
  {
    name: 'solidworks_mate_group_execution_check',
    description: 'Check after-inspect evidence for mate group macro execution: expected named mates exist, are unsuppressed, and report no solver/API errors.',
    inputSchema: { type: 'object', properties: { macro_manifest: { type: 'string' }, after_report: { type: 'string' }, out: { type: 'string' } }, required: ['macro_manifest', 'after_report'], additionalProperties: false }
  },
  {
    name: 'solidworks_mate_group_live_protocol',
    description: 'Generate a controlled per-group live SolidWorks work order for reviewed mate group macros: backup, selection evidence, macro run, rebuild, inspect, execution check, interference, and cleanup.',
    inputSchema: { type: 'object', properties: { macro_manifest: { type: 'string' }, validation_report: { type: 'string' }, model: { type: 'string' }, out: { type: 'string' }, markdown_out: { type: 'string' } }, required: ['macro_manifest', 'validation_report'], additionalProperties: false }
  },
  {
    name: 'solidworks_assembly_review_pipeline',
    description: 'Run the read-only assembly review pipeline from one inspect report and write diagnosis, interface index, repair plan, mate group plan, and manifest artifacts.',
    inputSchema: { type: 'object', properties: { report: { type: 'string' }, out_dir: { type: 'string' }, near_tolerance_m: { type: 'number' }, standard_part_regex: { type: 'string' } }, required: ['report'], additionalProperties: false }
  },
  {
    name: 'solidworks_worklog',
    description: 'Append a durable worklog event for multi-turn decisions, assumptions, verification, failures, and next steps.',
    inputSchema: {
      type: 'object',
      properties: {
        message: { type: 'string' },
        event: { type: 'string', enum: ['note','decision','assumption','verification','failure','manual_action','next_step'] },
        session_name: { type: 'string' },
        artifact: { type: 'array', items: { type: 'string' } },
        next: { type: 'string' },
        log: { type: 'string' },
        summary_out: { type: 'string' }
      },
      required: ['message'],
      additionalProperties: false
    }
  },
  {
    name: 'solidworks_handoff_bundle',
    description: 'Create a compact handoff bundle with inspect JSON, context pack, worklog summary, README, and manifest.',
    inputSchema: {
      type: 'object',
      properties: {
        report: { type: 'string' },
        worklog: { type: 'string' },
        focus: { type: 'string' },
        out_dir: { type: 'string' }
      },
      required: ['report'],
      additionalProperties: false
    }
  },
  {
    name: 'solidworks_tool_catalog',
    description: 'Generate a grouped catalog of all SolidWorks Codex MCP tools and when to use them.',
    inputSchema: { type: 'object', properties: { out: { type: 'string' }, json_out: { type: 'string' } }, additionalProperties: false }
  },
  {
    name: 'solidworks_offline_demo',
    description: 'Generate a 5-minute offline demo bundle for GitHub readers without requiring SolidWorks to be open.',
    inputSchema: { type: 'object', properties: { out_dir: { type: 'string' } }, additionalProperties: false }
  },
  {
    name: 'solidworks_preflight',
    description: 'Run deterministic environment/toolchain preflight before touching a real SolidWorks model.',
    inputSchema: { type: 'object', properties: { out: { type: 'string' } }, additionalProperties: false }
  },
  {
    name: 'solidworks_audit',
    description: 'Run the offline verification gate for this SolidWorks Codex toolchain.',
    inputSchema: { type: 'object', properties: { out: { type: 'string' } }, additionalProperties: false }
  },
  {
    name: 'solidworks_finalize',
    description: 'Generate the final readiness Markdown/JSON report after running audit.',
    inputSchema: { type: 'object', properties: { out: { type: 'string' }, json_out: { type: 'string' } }, additionalProperties: false }
  },  {
    name: 'solidworks_existing_mcp_tools',
    description: 'List tools exposed by installed npm solidworks-mcp-server in mock mode.',
    inputSchema: { type: 'object', properties: {}, additionalProperties: false }
  }
];

function respond(id, result) {
  if (id === undefined || id === null) return;
  process.stdout.write(JSON.stringify({ jsonrpc: '2.0', id, result }) + '\n');
}

function respondError(id, code, message, data) {
  if (id === undefined || id === null) return;
  process.stdout.write(JSON.stringify({ jsonrpc: '2.0', id, error: { code, message, data } }) + '\n');
}

function runSwctl(args) {
  return new Promise((resolve) => {
    const child = spawn('powershell.exe', ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', swctl, ...args], {
      cwd: workspace,
      windowsHide: true,
      stdio: ['ignore', 'pipe', 'pipe']
    });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (d) => { stdout += d.toString(); });
    child.stderr.on('data', (d) => { stderr += d.toString(); });
    child.on('error', (err) => resolve({ code: -1, stdout, stderr: `${stderr}${err.stack || err.message}` }));
    child.on('close', (code) => resolve({ code, stdout, stderr }));
  });
}

function textContent(text) {
  return [{ type: 'text', text }];
}

function parseMaybeJson(text) {
  try { return JSON.stringify(JSON.parse(text), null, 2); } catch { return text; }
}

async function callTool(name, input) {
  const args = [];
  switch (name) {
    case 'solidworks_probe':
      args.push('probe');
      if (input?.out) args.push('-Out', input.out);
      break;
    case 'solidworks_start_probe':
      args.push('start-probe');
      if (input?.out) args.push('-Out', input.out);
      break;
    case 'solidworks_inspect':
      args.push('inspect');
      if (input?.model) args.push('-Model', input.model);
      if (input?.out) args.push('-Out', input.out);
      break;
    case 'solidworks_start_inspect':
      args.push('start-inspect');
      if (input?.model) args.push('-Model', input.model);
      if (input?.out) args.push('-Out', input.out);
      break;
    case 'solidworks_backup':
      args.push('backup', '-Files', ...(input.files || []));
      if (input?.out) args.push('-Out', input.out);
      break;
    case 'solidworks_backup_status':
      args.push('backup-status', '-Report', input.report);
      if (input?.out) args.push('-Out', input.out);
      break;
    case 'solidworks_restore_backup':
      args.push('restore-backup', '-Report', input.report);
      if (input?.apply) args.push('-Apply');
      if (input?.out) args.push('-Out', input.out);
      break;
    case 'solidworks_set_dimension':
      args.push('set-dimension', '-Dimension', input.dimension, '-ValueM', String(input.value_m));
      if (input?.model) args.push('-Model', input.model);
      if (input?.save) args.push('-Save');
      if (input?.out) args.push('-Out', input.out);
      break;
    case 'solidworks_safe_set_dimension':
      args.push('safe-set-dimension', '-Model', input.model, '-Dimension', input.dimension, '-ValueM', String(input.value_m));
      if (input?.save) args.push('-Save');
      if (input?.out_dir) args.push('-OutDir', input.out_dir);
      if (input?.out) args.push('-Out', input.out);
      break;
    case 'solidworks_rebuild':
      args.push('rebuild');
      if (input?.model) args.push('-Model', input.model);
      if (input?.save) args.push('-Save');
      if (input?.out) args.push('-Out', input.out);
      break;
    case 'solidworks_export':
      args.push('export', '-Target', input.target);
      if (input?.model) args.push('-Model', input.model);
      if (input?.out) args.push('-Out', input.out);
      break;
    case 'solidworks_mass_properties':
      args.push('mass');
      if (input?.model) args.push('-Model', input.model);
      if (input?.out) args.push('-Out', input.out);
      break;
    case 'solidworks_compare_reports':
      args.push('compare', '-Before', input.before, '-After', input.after);
      if (input?.out) args.push('-Out', input.out);
      if (input?.json_out) args.push('-JsonOut', input.json_out);
      break;
    case 'solidworks_change_verify':
      args.push('change-verify', '-Report', input.delta);
      if ((input.allow_dimension || []).length) args.push('-AllowDimension', input.allow_dimension.join(','));
      if ((input.allow_component || []).length) args.push('-AllowComponent', input.allow_component.join(','));
      if ((input.allow_component_added || []).length) args.push('-AllowComponentAdded', input.allow_component_added.join(','));
      if ((input.allow_component_removed || []).length) args.push('-AllowComponentRemoved', input.allow_component_removed.join(','));
      if ((input.allow_feature_type || []).length) args.push('-AllowFeatureType', input.allow_feature_type.join(','));
      if (input?.require_allowed_change) args.push('-RequireAllowedChange');
      if (input?.out) args.push('-Out', input.out);
      break;
    case 'solidworks_component_state':
      args.push('component-state', '-Component', input.component, '-Action', input.action);
      if (input?.save) args.push('-Save');
      if (input?.out) args.push('-Out', input.out);
      break;
    case 'solidworks_feature_state':
      args.push('feature-state', '-Target', input.feature, '-Action', input.action);
      if (input?.model) args.push('-Model', input.model);
      if (input?.save) args.push('-Save');
      if (input?.out) args.push('-Out', input.out);
      break;
    case 'solidworks_interference_check':
      args.push('interference');
      if (input?.out) args.push('-Out', input.out);
      break;    case 'solidworks_template_macro':
      args.push('template-macro', '-Template', input.template);
      if (input?.out) args.push('-Out', input.out);
      if (input?.manifest) args.push('-Manifest', input.manifest);
      if (input?.outer_diameter_mm !== undefined) args.push('-OuterDiameterMm', String(input.outer_diameter_mm));
      if (input?.inner_diameter_mm !== undefined) args.push('-InnerDiameterMm', String(input.inner_diameter_mm));
      if (input?.length_mm !== undefined) args.push('-LengthMm', String(input.length_mm));
      if (input?.thickness_mm !== undefined) args.push('-ThicknessMm', String(input.thickness_mm));
      if (input?.center_bore_mm !== undefined) args.push('-CenterBoreMm', String(input.center_bore_mm));
      if (input?.hole_count !== undefined) args.push('-HoleCount', String(input.hole_count));
      if (input?.hole_pcd_mm !== undefined) args.push('-HolePcdMm', String(input.hole_pcd_mm));
      if (input?.hole_diameter_mm !== undefined) args.push('-HoleDiameterMm', String(input.hole_diameter_mm));
      if (input?.plate_width_mm !== undefined) args.push('-PlateWidthMm', String(input.plate_width_mm));
      if (input?.plate_height_mm !== undefined) args.push('-PlateHeightMm', String(input.plate_height_mm));
      if (input?.motor_hole_x_mm !== undefined) args.push('-MotorHoleXMm', String(input.motor_hole_x_mm));
      if (input?.motor_hole_y_mm !== undefined) args.push('-MotorHoleYMm', String(input.motor_hole_y_mm));
      if (input?.bearing_outer_diameter_mm !== undefined) args.push('-BearingOuterDiameterMm', String(input.bearing_outer_diameter_mm));
      if (input?.recess_depth_mm !== undefined) args.push('-RecessDepthMm', String(input.recess_depth_mm));
      break;    case 'solidworks_issue_report':
      args.push('issue-report', '-Report', input.report);
      if (input?.out) args.push('-Out', input.out);
      if (input?.json_out) args.push('-JsonOut', input.json_out);
      break;
    case 'solidworks_mate_macro':
      args.push('mate-macro', '-Mate', input.mate);
      if (input?.distance_mm !== undefined) args.push('-DistanceMm', String(input.distance_mm));
      if (input?.distance_min_mm !== undefined) args.push('-DistanceMinMm', String(input.distance_min_mm));
      if (input?.distance_max_mm !== undefined) args.push('-DistanceMaxMm', String(input.distance_max_mm));
      if (input?.angle_deg !== undefined) args.push('-AngleDeg', String(input.angle_deg));
      if (input?.angle_min_deg !== undefined) args.push('-AngleMinDeg', String(input.angle_min_deg));
      if (input?.angle_max_deg !== undefined) args.push('-AngleMaxDeg', String(input.angle_max_deg));
      if (input?.flip) args.push('-Flip');
      if (input?.out) args.push('-Out', input.out);
      if (input?.manifest) args.push('-Manifest', input.manifest);
      break;
    case 'solidworks_mate_group_macro':
      args.push('mate-group-macro', '-Report', input.mate_group_plan);
      if (input?.out_dir) args.push('-OutDir', input.out_dir);
      if (input?.manifest) args.push('-Out', input.manifest);
      break;
    case 'solidworks_mate_group_execute':
      args.push('mate-group-execute', '-Report', input.macro_manifest);
      if (input?.dry_run) args.push('-ValidateOnly');
      if (input?.out) args.push('-Out', input.out);
      break;    case 'solidworks_selection_report':
      args.push(input?.start ? 'start-selection-report' : 'selection-report');
      if (input?.out) args.push('-Out', input.out);
      break;    case 'solidworks_session_snapshot':
      args.push(input?.start ? 'start-session-snapshot' : 'session-snapshot');
      if (input?.name) args.push('-SessionName', input.name);
      if (input?.from_report) args.push('-FromReport', input.from_report);
      if (input?.out_dir) args.push('-OutDir', input.out_dir);
      break;    case 'solidworks_report_summary':
      args.push('summary', '-Report', input.report);
      if (input?.out) args.push('-Out', input.out);
      break;    case 'solidworks_design_review':
      args.push('design-review', '-Report', input.report);
      if (input?.intent) args.push('-Target', input.intent);
      if (input?.out) args.push('-Out', input.out);
      if (input?.json_out) args.push('-JsonOut', input.json_out);
      break;
    case 'solidworks_change_plan':
      args.push('change-plan', '-Report', input.report, '-Target', input.goal);
      if (input?.session_name) args.push('-SessionName', input.session_name);
      if (input?.out) args.push('-Out', input.out);
      if (input?.json_out) args.push('-JsonOut', input.json_out);
      break;    case 'solidworks_report_search':
      args.push('report-search', '-Report', input.report);
      if (input?.query) args.push('-Target', input.query);
      if (input?.kind) args.push('-Action', input.kind);
      if (input?.state) args.push('-Component', input.state);
      if (input?.out) args.push('-Out', input.out);
      if (input?.json_out) args.push('-JsonOut', input.json_out);
      break;
    case 'solidworks_report_context':
      args.push('report-context', '-Report', input.report);
      if (input?.focus) args.push('-Target', input.focus);
      if (input?.out) args.push('-Out', input.out);
      if (input?.json_out) args.push('-JsonOut', input.json_out);
      break;
    case 'solidworks_model_understand':
      args.push('model-understand', '-Report', input.report);
      if (input?.task) args.push('-Target', input.task);
      if (input?.view) args.push('-View', input.view);
      if (input?.out) args.push('-Out', input.out);
      if (input?.json_out) args.push('-JsonOut', input.json_out);
      break;
    case 'solidworks_assembly_diagnose':
      args.push('assembly-diagnose', '-Report', input.report);
      if (input?.out) args.push('-Out', input.out);
      if (input?.lock_root) args.push('-OutDir', input.lock_root);
      if (input?.near_tolerance_m !== undefined) args.push('-DistanceMm', String(input.near_tolerance_m * 1000));
      if (input?.standard_part_regex) args.push('-Target', input.standard_part_regex);
      break;
    case 'solidworks_assembly_repair_plan':
      args.push('assembly-repair-plan', '-Report', input.diagnosis);
      if (input?.out) args.push('-Out', input.out);
      if (input?.markdown_out) args.push('-JsonOut', input.markdown_out);
      break;
    case 'solidworks_interface_index':
      args.push('interface-index', '-Report', input.report);
      if (input?.out) args.push('-Out', input.out);
      if (input?.near_tolerance_m !== undefined) args.push('-DistanceMm', String(input.near_tolerance_m * 1000));
      if (input?.standard_part_regex) args.push('-Target', input.standard_part_regex);
      break;
    case 'solidworks_mate_group_plan':
      args.push('mate-group-plan', '-Report', input.repair_plan, '-FromReport', input.interface_index);
      if (input?.out) args.push('-Out', input.out);
      if (input?.markdown_out) args.push('-JsonOut', input.markdown_out);
      break;
    case 'solidworks_mate_group_validate':
      args.push('mate-group-validate', '-Report', input.mate_group_plan);
      if (input?.out) args.push('-Out', input.out);
      break;
    case 'solidworks_mate_selection_check':
      args.push('mate-selection-check', '-Report', input.macro_manifest, '-FromReport', input.selection_report);
      if (input?.expected_mate_name) args.push('-Mate', input.expected_mate_name);
      if (input?.out) args.push('-Out', input.out);
      break;
    case 'solidworks_mate_group_execution_check':
      args.push('mate-group-execution-check', '-Report', input.macro_manifest, '-After', input.after_report);
      if (input?.out) args.push('-Out', input.out);
      break;
    case 'solidworks_mate_group_live_protocol':
      args.push('mate-group-live-protocol', '-Report', input.macro_manifest, '-FromReport', input.validation_report);
      if (input?.model) args.push('-Model', input.model);
      if (input?.out) args.push('-Out', input.out);
      if (input?.markdown_out) args.push('-JsonOut', input.markdown_out);
      break;
    case 'solidworks_assembly_review_pipeline':
      args.push('assembly-review-pipeline', '-Report', input.report);
      if (input?.out_dir) args.push('-OutDir', input.out_dir);
      if (input?.near_tolerance_m !== undefined) args.push('-DistanceMm', String(input.near_tolerance_m * 1000));
      if (input?.standard_part_regex) args.push('-Target', input.standard_part_regex);
      break;
    case 'solidworks_worklog':
      args.push('worklog', '-Message', input.message);
      if (input?.event) args.push('-Action', input.event);
      if (input?.session_name) args.push('-SessionName', input.session_name);
      if (input?.log) args.push('-Out', input.log);
      if (input?.summary_out) args.push('-JsonOut', input.summary_out);
      if (input?.next) args.push('-Next', input.next);
      for (const artifact of (input?.artifact || [])) args.push('-Artifact', artifact);
      break;
    case 'solidworks_handoff_bundle':
      args.push('handoff-bundle', '-Report', input.report);
      if (input?.worklog) args.push('-FromReport', input.worklog);
      if (input?.focus) args.push('-Target', input.focus);
      if (input?.out_dir) args.push('-OutDir', input.out_dir);
      break;
    case 'solidworks_tool_catalog':
      args.push('tool-catalog');
      if (input?.out) args.push('-Out', input.out);
      if (input?.json_out) args.push('-JsonOut', input.json_out);
      break;
    case 'solidworks_offline_demo':
      args.push('offline-demo');
      if (input?.out_dir) args.push('-OutDir', input.out_dir);
      break;    case 'solidworks_preflight':
      args.push('preflight');
      if (input?.out) args.push('-Out', input.out);
      break;
    case 'solidworks_audit':
      args.push('audit');
      if (input?.out) args.push('-Out', input.out);
      break;
    case 'solidworks_finalize':
      args.push('finalize');
      if (input?.out) args.push('-Out', input.out);
      if (input?.json_out) args.push('-JsonOut', input.json_out);
      break;    case 'solidworks_existing_mcp_tools':
      args.push('mcp-tools');
      break;
    default:
      throw new Error(`Unknown tool: ${name}`);
  }
  const result = await runSwctl(args);
  const body = {
    command: ['powershell.exe', '-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', swctl, ...args],
    cwd: workspace,
    exit_code: result.code,
    stdout: parseMaybeJson(result.stdout.trim()),
    stderr: result.stderr.trim()
  };
  return { content: textContent(JSON.stringify(body, null, 2)), isError: result.code !== 0 };
}

async function handleMessage(msg) {
  if (msg.method === 'initialize') {
    respond(msg.id, {
      protocolVersion: msg.params?.protocolVersion || '2024-11-05',
      capabilities: { tools: {} },
      serverInfo: { name: 'solidworks-codex-mcp', version: '0.1.0' }
    });
    return;
  }
  if (msg.method === 'notifications/initialized') return;
  if (msg.method === 'tools/list') {
    respond(msg.id, { tools: toolSchemas });
    return;
  }
  if (msg.method === 'tools/call') {
    try {
      const result = await callTool(msg.params?.name, msg.params?.arguments || {});
      respond(msg.id, result);
    } catch (err) {
      respondError(msg.id, -32603, err.message || String(err), err.stack);
    }
    return;
  }
  if (msg.method === 'shutdown') {
    respond(msg.id, {});
    shuttingDown = true;
    return;
  }
  if (msg.method === 'exit') {
    process.exit(shuttingDown ? 0 : 1);
  }
  respondError(msg.id, -32601, `Method not found: ${msg.method}`);
}

process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => {
  buffer += chunk;
  const lines = buffer.split(/\r?\n/);
  buffer = lines.pop();
  for (const line of lines) {
    if (!line.trim()) continue;
    let msg;
    try { msg = JSON.parse(line); } catch (err) { continue; }
    handleMessage(msg).catch((err) => respondError(msg.id, -32603, err.message || String(err), err.stack));
  }
});










